// mappings_pruned.dart
// List of Regions
const List<String> regions = [
  'Amhara',
  'Oromia',
  'SNNP',
  'Sidama',
  'South West',
  'Tigray'
];
// Region → Zones
const Map<String, List<String>> regionZoneMapping = {
  "Amhara": [
    'Awi Zone',
    'Bahir Dar City Administration',
    'Central Gondar',
    'Dese City Administration',
    'East Gojjam',
    'Gonder City Administration',
    'North Gondar',
    'North Shoa',
    'North Wollo',
    'Oromia Special',
    'South Gondar',
    'South Wollo',
    'Wagmera',
    'West Gojjam',
    'West Gonder'
  ],
  "Tigray": [
    'Central Tigray',
    'East Tigray',
    'Mekele Special Zone',
    'North Western Tigray',
    'South Tigray',
    'West Tigray'
  ],
  "Oromia": [
    'Arsi',
    'Bale',
    'Borena ',
    'Buno Bedele',
    'East Bale',
    'East Harerghe',
    'East Shewa',
    'East Wellega',
    'Guji',
    'Horo Gudru Wellega',
    'Illubabora',
    'Jimma',
    'North Shewa',
    'Oromia Special Zone',
    'Qelem Wellega',
    'South West Shewa',
    'West Arsi',
    'West Harerghe',
    'West Shewa',
    'West Wellega'
  ],
  "South West": [
    'Bench Maji',
    'Bench Sheko',
    'Dawuro',
    'Kefa',
    'Konta',
    'Sheka',
    'West Omo '
  ],
  "Sidama": ['Sidama'],
  "SNNP": [
    'Basketo',
    'Gamo',
    'Gedeo',
    'Gofa',
    'Gurage',
    'Hadiya',
    'Halaba ',
    'Kambata',
    'Konso',
    'Siliti',
    'South Omo',
    'Wolayita',
    'Yem Special Woreda'
  ]
};
// Zone → Woredas
const Map<String, List<String>> zoneWoredaMapping = {
  "South Wollo": [
    'Albuko',
    'Hayke Town Administration',
    'Jama',
    'KelalaTown Administration',
    'Kombolcha Town Administration',
    'Legambo',
    'Legehida',
    'Mehal Saynit',
    'Mekane Selam Town Administration',
    'Tenta',
    'Wereyilu'
  ],
  "Awi Zone": [
    'Chageni Town Administration',
    'Dangela Town Administration',
    'EnjibaraTown Administration',
    'Fendika Town Administration',
    'Zigem'
  ],
  "West Tigray": ['Humera Town', 'Welkait'],
  "North Western Tigray": ['Tahtay-Adiyabo', 'Tahtay-Koraro'],
  "South Tigray": ['Maychew Town', 'Raya-Alamata', 'Raya-Azebo'],
  "East Tigray": ['Adigrat', 'Hawzein', 'Wukro'],
  "Central Tigray": ['Aksum', 'Kola-Tembeien'],
  "South Gondar": [
    'Addis Zemen Town Administration',
    'Debretabor Town Administration',
    'Dera',
    'Ebinat Town Administration',
    'Guna Begemedere',
    'Mekane Yesus Town Administration',
    'Nefas Mewecha Town Administration',
    'Wegeda Town Administration',
    'Wereta Town Administration'
  ],
  "North Wollo": [
    'Kobo Town Administration',
    'Lalibela Town Administration',
    'Mersa Town Administration',
    'Woldiya Town Administration'
  ],
  "Gonder City Administration": ['Gondar Town  Administration'],
  "Mekele Special Zone": ['Mekele Town'],
  "North Shewa": [
    'Abichugna',
    'Alaltuu',
    'Dagam',
    'Fiche City Administration',
    'Kimbibit',
    'Wuchale'
  ],
  "Kefa": ['Bonga City Administration', 'Chena', 'Gimbo '],
  "North Gondar": ['Dabat Town Administration', 'Debark Town Administration'],
  "Sidama": [
    'Aleta Chuko City Administration',
    'Aleta Wondo City Administration',
    'Arbigona ',
    'Bensa Daye ',
    'Blate Zuria ',
    'Bona',
    'Boricha',
    'Dara',
    'Habe Lalida (Hawala)',
    'Hawassa City Administration',
    'Hawassa Zuria ',
    'Leku City Administration',
    'Loka Abaya ',
    'Wondogenet City Administration',
    'Wonsho',
    'Yirgalem City Administration '
  ],
  "Hadiya": ['Badewocho ', 'Giba ', 'Gombora ', 'Hosana City Administration', 'Shashago ', 'Soro '],
  "Gedeo": ['Bula ', 'Dilla City Administration', 'Gedeb', 'Kochera', 'Wonago', 'Yergachefa'],
  "East Harerghe": ['Deder', 'Haromaya'],
  "Siliti": ['Dalocha', 'Hulbareg ', 'Sankura ', 'Silte ', 'Worabe City Administration'],
  "Dawuro": ['Disa ', 'Esra', 'Gesachere', 'Tercha City Administration'],
  "West Arsi": [
    'Adaba',
    'Dodola',
    'Gedeb Asasa',
    'Heben arsi',
    'Kofele',
    'Kokosa',
    'Kore',
    'Negele Arsi '
  ],
  "North Shoa": [
    'Alem Ketema Town Administration',
    'Arereti Town Administration',
    'Asagert',
    'Debere Birhan Town Administration',
    'Debresina Town Administration',
    'Enwari Town Administration',
    'Hagere Mariam',
    'Menze Keya Gebreal',
    'Mida Weremo',
    'Mojana Wadera',
    'Molale Town Administration',
    'Siya Debirna Wayu'
  ],
  "West Gojjam": [
    'Adet Town Administration',
    'Bure Town Administration',
    'Dembecha Town Administration',
    'Durbete Town Administration',
    'Finote Selam Town Administration',
    'Gonje Kolela',
    'Merawi Town Administration',
    'North Achefer',
    'South Mecha'
  ],
  "West Wellega": ['Gimbi City Administration', 'Najo'],
  "Wagmera": ['Sekota Town Administration'],
  "Gamo": ['Arbaminch City Administration', 'Deramalo ', 'Kemba Zuria ', 'Kutcha '],
  "Jimma": [
    'Botor Tolay',
    'Chora Boter',
    'Gera',
    'Goma',
    'Jimma City Administration',
    'Mana',
    'Omo Nado',
    'Omonada',
    'Saka Chokorsa',
    'Sokoru',
    'Tiro Afata'
  ],
  "Wolayita": [
    'Areka City Administration',
    ' Duguna Fango ',
    'Damot Gale ',
    'Humbo ',
    'Sodo City Administration',
    'Ufa '
  ],
  "Konta": ['Chida Town Administration', 'Konta '],
  "Dese City Administration": ['Dese Town Administration'],
  "Bench Sheko": ['Mizan City Administration', 'Sez Town Administration', 'South Bench '],
  "Bale": [
    'Agarfa',
    'Bale Robe City Administration',
    'Dello Menna',
    'Dinsho',
    'Gasera',
    'Ginir City Administration',
    'Goba',
    'Sinaana'
  ],
  "South West Shewa": [
    'Amaya',
    'Becho ',
    'Goro',
    'Ilu',
    'Kersa Malima',
    'Sodo Dache',
    'Tole',
    'Weliso',
    'Weliso City Administration'
  ],
  "Bahir Dar City Administration": ['Bahir Dar Town  Administration'],
  "Illubabora": ['Metu City Administration'],
  "Basketo": ['Basketo '],
  "Horo Gudru Wellega": [
    'Ababoo Guduruu',
    'Abay Chomen',
    'Abe dongoro',
    'Amuru',
    'Guduru',
    'Horo Buluk',
    'Jima Geneti',
    'Jima Rare',
    'Shambu City Administration'
  ],
  "East Shewa": [
    'Adama City Administration',
    'Bishoftu  City Administration',
    'Bora',
    'Boset',
    'Dugda',
    'Gido Kombolcha',
    'Liben Chukala',
    'Lome',
    'Modjo City Administration'
  ],
  "Halaba ": ['Atoti Ulo ', 'Halaba kulito City Administration'],
  "Gurage": [
    'Butagira City Administration',
    'Cheha ',
    'Gumer ',
    'Gunichera City Administration',
    'South Sodo ',
    'Welkita City Administration'
  ],
  "Kambata": [
    'Angacha City Administration',
    'Doyogena City Administration',
    'Durame City Administration',
    'Hadero Zuria ',
    'Kacha Bira '
  ],
  "East Gojjam": [
    'Amanuel Town Administration',
    'Aneded',
    'Baso Liben',
    'BichenaTown Adminstartion',
    'Debay Tilat Gen',
    'Debere Elias',
    'Debere Work Town Administration',
    'Debre Markos Town Administration',
    'Dejen Town Administration',
    'Gunde Woyen Town Administration',
    'Lumame Town Administration',
    'Mereto LemariamTown Adminstartion'
  ],
  "South Omo": ['Ginka City Administration', 'South Ari '],
  "Gofa": ['Geza Gofa ', 'Melekoza ', 'Sawla City Administration', 'Uba Debretsehay '],
  "Central Gondar": [
    'Amba Giorgis Town Administration',
    'Ayekel Town Administration',
    'Kola Deba Town Administration',
    'Shawra Town Administration',
    'Tach Armacho',
    'Takusa',
    'West Dembia'
  ],
  "Yem Special Woreda": ['Yem '],
  "Bench Maji": ['Gura-Ferda'],
  "Konso": ['Karat City Administration'],
  "West Harerghe": ['Habro'],
  "West Shewa": [
    'Ambo City Administration',
    'Dano',
    'Dendi',
    'Ejere',
    'Ejersa Lafo',
    'Ilu Gelan',
    'Jaldu',
    'Liban Jawi',
    'Nono',
    'Toke Kutaye'
  ],
  "East Wellega": [
    'Gida Ayana',
    'Gutoo Gida',
    'Leka Dulecha',
    'Sasiga',
    'Sibu Sire ',
    'Wayu Tuka'
  ],
  "Oromia Special": ['Bati Town  Administration', 'Kemise Town Administration'],
  "Oromia Special Zone": ['Burayu City Administration', 'Muloo', 'Sulultaa City administration'],
  "Arsi": [
    'Amigna',
    'Asella City Administration',
    'Diksis',
    'Digelu Tijo',
    'Hetosa',
    'Honkolo Wabe',
    'Limmu Bilbiloo',
    'Lode Hexosa',
    'Munesa',
    'Shirka',
    'Sire',
    'Tiyo',
    'Ziway Dugda'
  ],
  "West Gonder": ['Genda Wuha Town Administration', 'Metema'],
  "Buno Bedele": [
    'Bedele City Administration',
    'Borecha',
    'Chawaka',
    'Dabo Hana',
    'Didesa',
    'Gechi'
  ],
  "Sheka": ['Anderacha ', 'Masha  '],
  "Qelem Wellega": ['Dale Wabara'],
  "East Bale": ['Ginir', 'Gololcha', 'Lege Hidha', 'Sawena'],
  "Borena ": ['Moyale', 'Yabelo City Administration'],
  "West Omo ": ['Meaent Goldiya  ', 'Meaent Shasha '],
  "Guji": ['Negele borena City Administration'],
};
// Woreda → Markets
const Map<String, List<String>> woredaMarketMapping = {
  "Kombolcha Town Administration": ['kombolcha kebele 03 Gebeya'],
  "EnjibaraTown Administration": ['Enjbara'],
  "Humera Town": ['Humera'],
  "Tahtay-Koraro": ['Shire-Endaselassie'],
  "Maychew Town": ['Maychew'],
  "Tahtay-Adiyabo": ['Sheraro'],
  "Adigrat": ['Adigrat'],
  "Aksum": ['Aksum'],
  "Mekane Yesus Town Administration": ['Estie Mekane Yesus Gebeya '],
  "Woldiya Town Administration": ['Woldia Gebeya'],
  "Gondar Town  Administration": ['Gondar Kedamie  Gebeya '],
  "Mekele Town": ['Mekele Town'],
  "Fiche City Administration": ['Fiche'],
  "Bonga City Administration": ['Bonga'],
  "Dabat Town Administration": ['Dabat Gebeya'],
  "Aleta Wondo City Administration": ['Aleta wondo'],
  "Soro ": ['Gimbicho'],
  "Dilla City Administration": ['Dilla'],
  "Mekane Selam Town Administration": ['Mekane Selam gebeya'],
  "Haromaya": ['Harar'],
  "Wereyilu": ['Wereyilu Segno Gebeya '],
  "Hawassa City Administration": ['Hawassa '],
  "Dalocha": ['Dalocha'],
  "Gesachere": ['Gesa chere'],
  "Dodola": ['Dodola '],
  "Chena": ['Chena'],
  "Chageni Town Administration": ['Chagini'],
  "Mehal MedaTown Adminstartion": ['Mehal Meda'],
  "Finote Selam Town Administration": ['Fenot selam Gebeya'],
  "Debretabor Town Administration": ['Debretabor Segno Gebeya '],
  "Shashamene City Administration": ['Shashemene Town'],
  "Najo": ['Najo'],
  "Arbigona ": ['Yaye'],
  "Sekota Town Administration": ['Sekota Segno Gebeya'],
  "Kutcha ": ['Selamber'],
  "Botor Tolay": ['Wayu'],
  "Areka City Administration": ['Areka'],
  "Konta ": ['Ameya'],
  "Dese Town Administration": ['Desse Robit Gebaya'],
  "Mizan City Administration": ['Mizan-aman'],
  "Arbaminch City Administration": ['Arbaminchi'],
  "Dembecha Town Administration": ['Dembecha Gebeya'],
  "Debre Birhan Town Administration": ['Debere Birhan Kebele 08 Gebeya'],
  "Merawi Town Administration": ['Merawi Gebeya'],
  "Debark Town Administration": ['Debark Gebeya'],
  "Gimbi City Administration": ['Gimbi Town'],
  "Wereta Town Administration": ['Wereta Arada Gebeya '],
  "Dangela Town Administration": ['Dangla '],
  "Bale Robe City Administration": ['Bale Robe'],
  "Kersa Malima": ['Kersa Malima'],
  "Humbo ": ['Humbo'],
  "Bahir Dar Town  Administration": ['Bahir Dar kebele 04'],
  "Wukro": ['Wukro'],
  "Metu City Administration": ['Metu'],
  "Basketo ": ['Laska'],
  "Shambu City Administration": ['Shambu Town'],
  "Tenta": ['tenta Gebeya'],
  "Bishoftu  City Administration": ['Bishoftu'],
  "Halaba kulito City Administration": ['Halaba'],
  "Debresina Town Administration": ['Debresina Gebeya'],
  "Dugda": ['Meki '],
  "Adama City Administration": ['Adama City'],
  "Badewocho ": ['Shone'],
  "Butagira City Administration": ['Butajira'],
  "Tercha City Administration": ['Tercha'],
  "Cheha ": ['Indebir'],
  "Alem Ketema Town Administration": ['Alem Ketema Kedame Gebeya'],
  "Wegeda Town Administration": ['Wegeda Gebeya'],
  "Lalibela Town Administration": ['Lalibela Ketema Gebeya'],
  "Bensa Daye ": ['Daye'],
  "Durame City Administration": ['Durame'],
  "Hadero Zuria ": ['Hadero'],
  "Sodo City Administration": ['Wolaita Soddo'],
  "Bure Town Administration": ['Bure Woreda'],
  "Welkita City Administration": ['Wolkite'],
  "Dejen Town Administration": ['Dejen Gebeya'],
  "Ginka City Administration": ['Jinka'],
  "Sawla City Administration": ['Sawula'],
  "Shawra Town Administration": ['Shawura Gebeya'],
  "Yem ": ['Saja'],
  "Hosana City Administration": ['Hosaena'],
  "Gura-Ferda": ['Biftu'],
  "Karat City Administration": ['Karat'],
  "Boricha": ['Yirba'],
  "Habro": ['Galamso'],
  "Deder": ['Deder'],
  "Kofele": ['Kofale'],
  "Ilu Gelan": ['Ijaji'],
  "Sasiga": ['Goto 24'],
  "Debre Markos Town Administration": ['Debre Markos Huseta Gebeya'],
  "Welkait": ['Adi-Remets'],
  "Dendi": ['Ginci'],
  "Bati Town  Administration": ['Bati Segno Gebeya'],
  "Kemise Town Administration": ['Kemise Hamus Gebeya '],
  "Burayu City Administration": ['Burayu'],
  "Kola Deba Town Administration": ['Kola Diba'],
  "Modjo City Administration": ['Mojo'],
  "Sibu Sire ": ['Sibusire'],
  "Gida Ayana": ['Gidda Ayana'],
  "Hetosa": ['Itaya'],
  "Gedeb": ['Gedeb'],
  "Worabe City Administration": ['Worabae'],
  "Ejersa Lafo": ['Olonkomi'],
  "Arereti Town Administration": ['Arerti Gebeya '],
  "Gido Kombolcha": ['Batu'],
  "Adet Town Administration": ['Adet Gebeya '],
  "Metema": ['Kokit  Metema Gebeya'],
  "Bedele City Administration": ['Bedele'],
  "Jaldu": ['Gojo'],
  "Becho ": ['Tullo Bolo'],
  "BichenaTown Adminstartion": ['Bichena Gebeya'],
  "Kola-Tembeien": ['Abi-Adi'],
  "Masha  ": ['Masha'],
  "Dale Wabara": ['Kake'],
  "Limmu Bilbiloo": ['Bokoji'],
  "Jima Geneti": ['Harato'],
  "Goma": ['Agaro', 'Goma'],
  "Asella City Administration": ['Asella'],
  "Saka Chokorsa": ['Saka '],
  "Gasera": ['Gasara'],
  "Borecha": ['Yanfa'],
  "Sokoru": ['Sokoru'],
  "Mersa Town Administration": ['Meresa  Gebeya'],
  "Kobo Town Administration": ['Kobo ketema'],
  "Hagere Mariam": ['Shola gebeya'],
  "Hayke Town Administration": ['Hayike'],
  "Enwari Town Administration": ['Enewari'],
  "Legambo": ['Akeseta'],
  "KelalaTown Administration": ['Kelala'],
  "Menze Keya Gebreal": ['Zemereo'],
  "Asagert": ['Ginager'],
  "Siya Debirna Wayu": ['Deneba'],
  "Albuko": ['Salmen'],
  "Mida Weremo": ['Meragna'],
  "Aneded": ['Amber'],
  "South Bench ": ['Debere Work '],
  "North Achefer": ['Liben'],
  "Nefas Mewecha Town Administration": ['Nefas Mewucha'],
  "Amba Giorgis Town Administration": ['Amba Georgies'],
  "Guna Begemedere": ['Kimer Dingay'],
  "Takusa": ['Delgie'],
  "Gunde Woyen Town Administration": ['Gunde woyin'],
  "Ebinat Town Administration": ['Ebenat Ketema'],
  "Lumame Town Administration": ['Lumame'],
  "Gonje Kolela": ['Addis Alem'],
  "Fendika Town Administration": ['Fendika'],
  "West Dembia": ['Chuahit'],
  "Genda Wuha Town Administration": ['Genda wuha'],
  "Mehal Saynit": ['Deansa'],
  "Legehida": ['Weyin Amba'],
  "Amanuel Town Administration": ['Amanuel'],
  "Zigem": ['kelaji'],
  "South Mecha": ['Mehal Genet Gebeya'],
  "Tach Armacho": ['Sanja'],
  "Durbete Town Administration": ['Durbete'],
  "Dera": ['Dera Amebesamie'],
  "Ayekel Town Administration": ['Aykel'],
  "Debay Tilat Gen": ['Kuye'],
  "Debere Work Town Administration": ['Debere Work'],
  "Addis Zemen Town Administration": ['Addis Zemen'],
  "Mojana Wadera": ['Sela dengay'],
  "Molale Town Administration": ['Molalalie'],
  "Jama": ['Degolo'],
  "Horo Buluk": ['Sakele'],
  "Goro": ['Goro South West Shewa'],
  "Ilu": ['Teji'],
  "Leka Dulecha": ['Getema'],
  "Gutoo Gida": ['Uke'],
  "Toke Kutaye": ['Gudar'],
  "Tole": ['Bantu'],
  "Nono": ['Silki Amba'],
  "Diga": ['Ifa'],
  "Ababoo Guduruu": ['Dedu'],
  "Mereto LemariamTown Adminstartion": ['Merto Lemariam'],
  "Lome": ['koka'],
  "Boset": ['walenchiti'],
  "Abichugna": ['Mandida'],
  "Liban Jawi": ['Babicha'],
  "Jima Rare": ['Wayu Jima Rare'],
  "Bora": ['bote'],
  "Sodo Dache": ['Tare'],
  "Muloo": ['Hoja Dure'],
  "Amaya": ['Gindo'],
  "Dagam": ['Hambiso'],
  "Wayu Tuka": ['Gute'],
  "Liben Chukala": ['Adulala'],
  "Weliso": ['Dilela'],
  "Gechi": ['Gechi'],
  "Munesa": ['Kersa'],
  "Heben arsi": ['Goljota'],
  "Amigna": ['Adele'],
  "Shirka": ['Gobesa'],
  "Goba": ['Goba'],
  "Kokosa": ['Kokosaa'],
  "Sulultaa City administration": ['Sululta'],
  "Diksis": ['Hamde'],
  "Dello Menna": ['Menna'],
  "Chora Boter": ['Bagi'],
  "Tiro Afata": ['Dimtu'],
  "Lege Hidha": ['Beltu'],
  "Dabo Hana": ['Kone'],
  "Dinsho": ['Dinsho'],
  "Moyale": ['Moyale'],
  "Chawaka": ['Ilu harer'],
  "Lode Hexosa": ['Huruta'],
  "Alaltuu": ['Mikawa'],
  "Digelu Tijo": ['Sagure'],
  "Agarfa": ['Agarfa'],
  "Ginir": ['Ginir'],
  "Omonada": ['Asandabo'],
  "Adaba": ['Adaba'],
  "Gololcha": ['Jara'],
  "Sawena": ['Micha'],
  "Wuchale": ['Muke turi'],
  "Ejere": ['Addis Alem Ejere'],
  "Gedeb Asasa": ['Asasa'],
  "Mana": ['Yabu'],
  "Gera": ['Chira'],
  "Kore": ['Kore'],
  "Weliso City Administration": ['Weliso Town'],
  "Sez Town Administration": ['Sez'],
  "Sinaana": ['selka'],
  "Dano": ['Sayo'],
  "Meaent Goldiya  ": ['Bachuma '],
  "Meaent Shasha ": ['Jemu '],
  "Wonago": ['Wonago'],
  "Angacha City Administration": ['Angacha '],
  "Sankura ": ['Alemgebaya '],
  "South Sodo ": ['Kela South Sodo'],
  "Melekoza ": ['Laha '],
  "South Ari ": ['Gazer '],
  "Silte ": ['Kibet '],
  "Honkolo Wabe": ['Siltana'],
  "Gunichera City Administration": ['Gunechere'],
  "Kochera": ['Kochera'],
  "Gombora ": ['Habicho '],
  "Bula ": ['Bule'],
  "Yergachefa": ['Yergachefa'],
  "Ufa ": ['Ufa Segno Gebeya'],
  "Giba ": ['Umacho '],
  "Geza Gofa ": ['Dede'],
  "Uba Debretsehay ": ['Zaba'],
  " Duguna Fango ": ['Bitena'],
  "Deramalo ": ['Wacha '],
  "Omo Nado": ['Omo nada'],
  "Hawassa Zuria ": ['Dore'],
  "Yirgalem City Administration ": ['Sedetegna'],
  "Gimbo ": ['Ufa '],
  "Bona": ['Bona 01'],
  "Habe Lalida (Hawala)": ['Haweela'],
  "Shashago ": ['Bonosha '],
  "Kacha Bira ": ['Shinshicho '],
  "Yabelo City Administration": ['Yabello'],
  "Damot Gale ": ['Damot Gale Makesegno Gebeya'],
  "Hulbareg ": ['Kerata '],
  "Leku City Administration": ['Leku '],
  "Wondogenet City Administration": ['Kela'],
  "Baso Liben": ['Yejube'],
  "Kemba Zuria ": ['Kemba '],
  "Atoti Ulo ": ['Guba '],
  "Doyogena City Administration": ['Doyogena '],
  "Gumer ": ['Bole'],
  " Sebeta City Administration": ['Sabata '],
  "Aleta Chuko City Administration": ['Gudumalee'],
  "Anderacha ": ['Gicha'],
  "Esra": ['Esra Bali '],
  "Ginir City Administration": ['Dalo Sebro'],
  "Loka Abaya ": ['Hantate '],
  "Chida Town Administration": ['Chida'],
  "Ziway Dugda": ['Ogolcho'],
  "Negele borena City Administration": ['Negele Borana'],
  "Guduru": ['Kombolcha-wellega'],
  "Wonsho": ['Bokaso'],
  "Didesa": ['Dambi'],
  "Blate Zuria ": ['Balela '],
  "Hawzein": ['Hawzen'],
  "Dara": ['Kawado'],
  "Abay Chomen": ['Finchaha'],
  "Jimma City Administration": ['Jimma Town'],
  "Ambo City Administration": ['Ambo Town'],
  "Kimbibit": ['Sheno'],
  "Amuru": ['Obora'],
  "Raya-Azebo": ['Mehoni'],
  "Sire": ['Sire'],
  "Debere Elias": ['Debere Elias Gebeya'],
  "Tiyo": ['Goleja'],
  "Negele Arsi ": ['Negelle Arsi'],
  "Abe dongoro": ['Tullu Wayu'],
  "Disa ": ['Disa '],
  "Raya-Alamata": ['Alamata'],
};
// Market → Crops
const Map<String, List<String>> marketCropNameMapping = {
  "kombolcha kebele 03 Gebeya": [
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Enjbara": ['Banana', 'Maize', 'Onion', 'Potato', 'Teff', 'Wheat'],
  "Humera": ['Teff', 'Wheat'],
  "Shire-Endaselassie": [
    'Banana',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Maychew": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Sheraro": [
    'Banana',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Adigrat": [
    'Banana',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Aksum": [
    'Avocado',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Estie Mekane Yesus Gebeya ": ['Maize', 'Teff', 'Wheat'],
  "Woldia Gebeya": ['Maize', 'Teff', 'Wheat'],
  "Gondar Kedamie  Gebeya ": [
    'Avocado',
    'Banana',
    'Garlic',
    'Green Mung',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Mekele Town": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Fiche": ['Maize', 'Teff', 'Wheat'],
  "Bonga": [
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dabat Gebeya": ['Maize', 'Sorghum', 'Teff', 'Wheat'],
  "Aleta wondo": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Gimbicho": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dilla": ['Banana', 'Maize', 'Malt Barely', 'Onion', 'Potato', 'Teff', 'Wheat'],
  "Mekane Selam gebeya": ['Banana', 'Maize', 'Mango', 'Onion', 'Potato', 'Teff', 'Wheat'],
  "Harar": ['Maize', 'Teff', 'Wheat'],
  "Wereyilu Segno Gebeya ": ['Maize', 'Onion', 'Potato', 'Teff', 'Tomato'],
  "Hawassa ": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dalocha": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Gesa chere": ['Banana', 'Bean', 'Maize', 'Malt Barely', 'Sorghum', 'Teff', 'Wheat'],
  "Dodola ": [
    'Banana',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Chena": [
    'Banana',
    'Bean',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Chagini": ['Maize', 'Onion', 'Teff'],
  "Mehal Meda": ['Maize', 'Onion', 'Teff', 'Wheat'],
  "Fenot selam Gebeya": ['Banana', 'Maize', 'Onion', 'Potato', 'Teff', 'Wheat'],
  "Debretabor Segno Gebeya ": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Shashemene Town": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Najo": ['Banana', 'Garlic', 'Maize', 'Onion', 'Potato', 'Sorghum', 'Tomato'],
  "Yaye": ['Maize', 'Malt Barely', 'Potato', 'Teff', 'Wheat'],
  "Sekota Segno Gebeya": ['Banana', 'Maize', 'Teff'],
  "Selamber": [
    'Avocado',
    'Banana',
    'Green Mung',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Wayu": ['Maize', 'Teff', 'Wheat'],
  "Areka": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Ameya": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Desse Robit Gebaya": ['Banana', 'Maize', 'Onion', 'Sorghum', 'Teff', 'Wheat'],
  "Mizan-aman": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Arbaminchi": [
    'Avocado',
    'Banana',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dembecha Gebeya": ['Maize', 'Onion', 'Teff', 'Wheat'],
  "Debere Birhan Kebele 08 Gebeya": [
    'Maize',
    'Malt Barely',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Merawi Gebeya": ['Maize', 'Onion', 'Teff', 'Wheat'],
  "Debark Gebeya": ['Banana', 'Bean', 'Maize', 'Onion', 'Potato', 'Teff', 'Tomato', 'Wheat'],
  "Gimbi Town": ['Banana', 'Maize', 'Teff'],
  "Wereta Arada Gebeya ": ['Banana', 'Garlic', 'Local Rice', 'Maize', 'Onion', 'Potato', 'Teff'],
  "Dangla ": ['Maize', 'Malt Barely', 'Potato', 'Teff', 'Wheat'],
  "Bale Robe": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kersa Malima": ['Banana', 'Maize', 'Teff', 'Wheat'],
  "Humbo": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Bahir Dar kebele 04": [
    'Banana',
    'Local Rice',
    'Maize',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Wukro": ['Banana', 'Maize', 'Teff'],
  "Metu": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Laska": ['Banana', 'Bean', 'Maize', 'Potato', 'Sesame', 'Teff', 'Wheat'],
  "Shambu Town": [
    'Avocado',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "tenta Gebeya": ['Banana', 'Local Rice', 'Maize', 'Sorghum', 'Wheat'],
  "Bishoftu": ['Banana', 'Bean', 'Local Rice', 'Maize', 'Malt Barely', 'Tomato'],
  "Halaba": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Debresina Gebeya": ['Maize', 'Teff', 'Wheat'],
  "Meki ": ['Banana', 'Maize', 'Malt Barely', 'Onion', 'Potato', 'Teff', 'Tomato', 'Wheat'],
  "Adama City": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Shone": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato'
  ],
  "Butajira": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Tercha": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Indebir": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Alem Ketema Kedame Gebeya": ['Maize', 'Teff', 'Tomato'],
  "Wegeda Gebeya": ['Banana', 'Maize', 'Teff'],
  "Lalibela Ketema Gebeya": ['Maize', 'Sorghum', 'Teff', 'Wheat'],
  "Daye": [
    'Avocado',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Durame": ['Banana', 'Bean', 'Garlic', 'Maize', 'Onion', 'Potato', 'Teff', 'Tomato', 'Wheat'],
  "Hadero": [
    'Avocado',
    'Banana',
    'Bean',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Wolaita Soddo": [
    'Banana',
    'Garlic',
    'Green Mung',
    'Maize',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Bure Woreda": ['Banana', 'Maize', 'Wheat'],
  "Wolkite": ['Garlic', 'Maize', 'Onion', 'Teff', 'Tomato'],
  "Dejen Gebeya": ['Maize', 'Potato', 'Teff', 'Wheat'],
  "Jinka": [
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Sawula": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Green Mung',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Shawura Gebeya": [
    'Banana',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato'
  ],
  "Saja": ['Banana', 'Maize', 'Teff', 'Wheat'],
  "Hosaena": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Biftu": ['Bean', 'Maize', 'Onion', 'Sesame', 'Sorghum', 'Teff', 'Tomato', 'Wheat'],
  "Karat": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Green Mung',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Yirba": ['Avocado', 'Bean', 'Maize', 'Onion', 'Potato', 'Teff', 'Tomato', 'Wheat'],
  "Galamso": [
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Deder": [
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kofale": ['Banana', 'Maize', 'Malt Barely', 'Potato', 'Teff', 'Wheat'],
  "Ijaji": ['Banana', 'Maize', 'Teff'],
  "Goto 24": ['Banana', 'Bean', 'Maize', 'Onion', 'Sorghum', 'Teff', 'Sesame'],
  "Debre Markos Huseta Gebeya": ['Banana', 'Teff'],
  "Adi-Remets": ['Teff'],
  "Ginci": ['Garlic', 'Maize', 'Malt Barely', 'Onion', 'Teff', 'Tomato', 'Wheat'],
  "Bati Segno Gebeya": ['Banana', 'Maize', 'Teff'],
  "Kemise Hamus Gebeya ": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff'
  ],
  "Burayu": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kola Diba": ['Banana', 'Maize', 'Teff'],
  "Mojo": [
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Sibusire": ['Banana', 'Maize', 'Teff'],
  "Gidda Ayana": ['Teff'],
  "Itaya": ['Maize', 'Sorghum', 'Teff', 'Wheat'],
  "Gedeb": ['Bean', 'Garlic', 'Maize', 'Onion', 'Potato', 'Soybean', 'Teff', 'Tomato', 'Wheat'],
  "Worabae": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Olonkomi": ['Banana', 'Potato', 'Teff', 'Tomato', 'Wheat'],
  "Arerti Gebeya ": ['Teff', 'Wheat'],
  "Batu": [
    'Avocado',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Adet Gebeya ": ['Onion', 'Teff'],
  "Kokit  Metema Gebeya": ['Banana', 'Teff'],
  "Bedele": [
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Gojo": ['Banana', 'Maize'],
  "Tullo Bolo": ['Banana', 'Teff', 'Tomato'],
  "Bichena Gebeya": ['Garlic', 'Onion', 'Teff'],
  "Abi-Adi": ['Teff'],
  "Masha": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kake": ['Bean', 'Maize', 'Teff', 'Wheat'],
  "Bokoji": ['Maize', 'Wheat'],
  "Harato": ['Banana', 'Teff'],
  "Agaro": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Asella": ['Banana', 'Onion'],
  "Saka ": [
    'Avocado',
    'Banana',
    'Garlic',
    'Green Mung',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Gasara": ['Onion', 'Potato', 'Teff', 'Wheat'],
  "Yanfa": ['Tomato'],
  "Sokoru": ['Onion'],
  "Meresa  Gebeya": ['Red Pepper', 'Teff'],
  "Kobo ketema": ['Banana', 'Garlic', 'Red Pepper', 'Teff', 'Wheat'],
  "Shola gebeya": ['Teff', 'Wheat'],
  "Hayike": [
    'Banana',
    'Garlic',
    'Green Mung',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Enewari": ['Teff'],
  "Akeseta": ['Teff'],
  "Kelala": [
    'Banana',
    'Bean',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Zemereo": ['Maize', 'Teff', 'Wheat'],
  "Ginager": ['Maize', 'Onion', 'Teff', 'Tomato', 'Wheat'],
  "Deneba": ['Teff'],
  "Salmen": ['Onion', 'Red Pepper', 'Teff', 'Wheat'],
  "Meragna": ['Maize', 'Onion', 'Potato', 'Red Pepper', 'Teff', 'Tomato', 'Wheat'],
  "Amber": ['Teff'],
  "Debere Work ": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Teff',
    'Tomato'
  ],
  "Liben": ['Teff'],
  "Nefas Mewucha": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Amba Georgies": ['Banana', 'Onion', 'Potato', 'Teff', 'Tomato'],
  "Kimer Dingay": ['Banana', 'Maize', 'Teff', 'Wheat'],
  "Delgie": ['Banana', 'Onion', 'Potato', 'Teff'],
  "Gunde woyin": ['Banana', 'Maize', 'Onion', 'Red Pepper', 'Sesame', 'Soybean', 'Teff', 'Wheat'],
  "Ebenat Ketema": ['Banana', 'Maize', 'Red Pepper', 'Teff', 'Wheat'],
  "Lumame": ['Maize', 'Onion', 'Red Pepper', 'Sorghum', 'Teff', 'Tomato', 'Wheat'],
  "Addis Alem": ['Mango', 'Teff'],
  "Fendika": ['Banana', 'Maize', 'Onion', 'Potato', 'Sorghum', 'Soybean', 'Teff', 'Tomato'],
  "Chuahit": ['Banana', 'Garlic', 'Maize', 'Onion', 'Potato', 'Sorghum', 'Teff', 'Tomato'],
  "Genda wuha": ['Onion', 'Potato', 'Teff', 'Tomato'],
  "Deansa": ['Maize', 'Onion', 'Potato', 'Teff', 'Wheat'],
  "Weyin Amba": ['Banana', 'Teff'],
  "Amanuel": ['Teff'],
  "kelaji": ['Maize', 'Onion', 'Red Pepper', 'Teff'],
  "Mehal Genet Gebeya": ['Maize', 'Onion', 'Potato', 'Sesame', 'Teff'],
  "Sanja": ['Banana', 'Maize', 'Teff'],
  "Durbete": ['Banana', 'Garlic', 'Local Rice', 'Maize', 'Onion', 'Potato', 'Teff', 'Tomato'],
  "Dera Amebesamie": ['Banana', 'Maize', 'Teff', 'Wheat'],
  "Aykel": ['Teff'],
  "Kuye": ['Maize', 'Onion', 'Red Pepper', 'Teff'],
  "Debere Work": ['Maize', 'Soybean', 'Teff', 'Wheat'],
  "Addis Zemen": ['Garlic', 'Maize', 'Onion', 'Potato', 'Teff', 'Tomato'],
  "Sela dengay": ['Teff', 'Wheat'],
  "Molalalie": ['Maize', 'Teff'],
  "Degolo": ['Local Rice', 'Maize', 'Onion', 'Potato', 'Red Pepper', 'Tomato'],
  "Sakele": ['Maize', 'Malt Barely', 'Potato', 'Soybean', 'Teff', 'Wheat'],
  "Goro South West Shewa": ['Banana', 'Maize', 'Red Pepper', 'Teff'],
  "Teji": ['Banana', 'Garlic', 'Maize', 'Onion', 'Potato', 'Teff', 'Tomato', 'Wheat'],
  "Getema": [
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Uke": ['Banana', 'Maize', 'Mango', 'Onion', 'Sorghum', 'Sesame', 'Teff', 'Tomato', 'Wheat'],
  "Gudar": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Bantu": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Silki Amba": [
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Ifa": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dedu": ['Banana', 'Maize', 'Sesame', 'Teff', 'Wheat'],
  "Merto Lemariam": ['Garlic', 'Local Rice', 'Maize', 'Red Pepper', 'Tomato'],
  "koka": [
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "walenchiti": [
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Mandida": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Babicha": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Wayu Jima Rare": [
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "bote": [
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Tare": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Hoja Dure": ['Banana', 'Teff'],
  "Gindo": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Hambiso": ['Banana', 'Maize', 'Onion', 'Teff', 'Tomato'],
  "Gute": ['Banana', 'Maize', 'Red Pepper', 'Teff'],
  "Adulala": [
    'Banana',
    'Bean',
    'Maize',
    'Malt Barely',
    'Onion',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dilela": [
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Gechi": [
    'Banana',
    'Bean',
    'Green Mung',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kersa": [
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Goljota": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Adele": [
    'Banana',
    'Maize',
    'Malt Barely',
    'Onion',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Gobesa": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Goba": [
    'Banana',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kokosaa": [
    'Banana',
    'Bean',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Sululta": ['Banana', 'Bean', 'Garlic', 'Onion', 'Potato', 'Teff', 'Tomato', 'Wheat'],
  "Hamde": [
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Menna": [
    'Banana',
    'Bean',
    'Garlic',
    'Green Mung',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Bagi": [
    'Banana',
    'Bean',
    'Maize',
    'Malt Barely',
    'Onion',
    'Sesame',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dimtu": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Beltu": [
    'Banana',
    'Bean',
    'Green Mung',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kone": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dinsho": ['Banana', 'Garlic', 'Maize', 'Malt Barely', 'Potato', 'Soybean', 'Teff', 'Wheat'],
  "Moyale": [
    'Avocado',
    'Banana',
    'Bean',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Ilu harer": [
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Huruta": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Mikawa": ['Banana', 'Maize', 'Malt Barely', 'Teff', 'Wheat'],
  "Sagure": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Agarfa": [
    'Avocado',
    'Banana',
    'Garlic',
    'Green Mung',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Ginir": [
    'Banana',
    'Garlic',
    'Green Mung',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Asandabo": ['Banana', 'Garlic', 'Onion', 'Potato', 'Red Pepper', 'Teff', 'Tomato'],
  "Adaba": [
    'Banana',
    'Garlic',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Jara": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Micha": ['Banana', 'Maize', 'Mango', 'Onion', 'Potato', 'Sorghum', 'Teff', 'Tomato', 'Wheat'],
  "Muke turi": [
    'Banana',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Addis Alem Ejere": [
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Asasa": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Yabu": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Chira": ['Avocado', 'Garlic', 'Maize', 'Onion', 'Potato', 'Sorghum', 'Teff', 'Tomato', 'Wheat'],
  "Kore": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Weliso Town": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Goma": [
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Sez": [
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "selka": ['Banana', 'Malt Barely', 'Onion', 'Red Pepper', 'Sorghum', 'Teff', 'Tomato', 'Wheat'],
  "Sayo": ['Banana', 'Garlic', 'Maize', 'Onion', 'Potato', 'Red Pepper', 'Sorghum', 'Teff', 'Tomato'],
  "Bachuma ": [
    'Avocado',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Sesame',
    'Teff',
    'Tomato'
  ],
  "Jemu ": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Sesame',
    'Teff',
    'Tomato'
  ],
  "Wonago": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Angacha ": ['Maize', 'Sorghum', 'Teff', 'Tomato', 'Wheat'],
  "Alemgebaya ": [
    'Banana',
    'Bean',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kela South Sodo": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Laha ": [
    'Avocado',
    'Green Mung',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Gazer ": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kibet ": ['Banana', 'Bean', 'Maize', 'Onion', 'Potato', 'Teff', 'Tomato', 'Wheat'],
  "Siltana": [
    'Banana',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Gunechere": [
    'Avocado',
    'Local Rice',
    'Maize',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Kochera": ['Banana', 'Garlic', 'Potato', 'Red Pepper', 'Teff', 'Tomato'],
  "Habicho ": ['Banana', 'Bean', 'Maize', 'Malt Barely', 'Sorghum', 'Teff', 'Wheat'],
  "Bule": ['Sesame', 'Teff'],
  "Yergachefa": [
    'Avocado',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Ufa Segno Gebeya": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Umacho ": [
    'Avocado',
    'Banana',
    'Green Mung',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dede": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Green Mung',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Zaba": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Bitena": [
    'Avocado',
    'Banana',
    'Bean',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Teff',
    'Wheat'
  ],
  "Wacha ": ['Banana', 'Maize', 'Teff'],
  "Omo nada": ['Garlic', 'Onion', 'Potato', 'Tomato'],
  "Dore": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Sedetegna": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Ufa ": ['Maize', 'Potato', 'Teff', 'Wheat'],
  "Bona 01": [
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Haweela": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Bonosha ": [
    'Banana',
    'Bean',
    'Maize',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Shinshicho ": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Yabello": [
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Damot Gale Makesegno Gebeya": ['Maize', 'Potato', 'Teff', 'Wheat'],
  "Kerata ": ['Maize', 'Onion', 'Potato', 'Sorghum', 'Teff', 'Tomato', 'Wheat'],
  "Leku ": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato'
  ],
  "Kela": [
    'Avocado',
    'Banana',
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Yejube": ['Teff'],
  "Kemba ": ['Avocado', 'Banana', 'Maize', 'Mango', 'Onion', 'Potato', 'Sorghum', 'Teff', 'Tomato', 'Wheat'],
  "Guba ": ['Bean', 'Garlic', 'Maize', 'Potato', 'Red Pepper', 'Sorghum', 'Soybean', 'Teff', 'Wheat'],
  "Doyogena ": [
    'Avocado',
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Bole": ['Banana', 'Local Rice'],
  "Sabata ": ['Banana', 'Maize', 'Onion', 'Tomato'],
  "Gudumalee": ['Banana', 'Bean', 'Local Rice', 'Maize', 'Wheat'],
  "Gicha": ['Banana'],
  "Esra Bali ": ['Banana'],
  "Dalo Sebro": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Hantate ": [
    'Bean',
    'Garlic',
    'Maize',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Chida": ['Maize', 'Onion', 'Red Pepper', 'Sorghum', 'Teff', 'Wheat'],
  "Ogolcho": [
    'Banana',
    'Bean',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Negele Borana": ['Malt Barely', 'Onion', 'Potato', 'Soybean', 'Teff', 'Wheat'],
  "Kombolcha-wellega": ['Sorghum', 'Teff'],
  "Bokaso": [
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Dambi": ['Onion', 'Red Pepper'],
  "Balela ": [
    'Bean',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Onion',
    'Potato',
    'Red Pepper',
    'Sesame',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Hawzen": ['Banana', 'Maize', 'Teff', 'Wheat'],
  "Kawado": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Potato',
    'Red Pepper',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Finchaha": ['Banana', 'Onion'],
  "Jimma Town": [
    'Avocado',
    'Banana',
    'Garlic',
    'Local Rice',
    'Maize',
    'Malt Barely',
    'Mango',
    'Onion',
    'Pineapple',
    'Potato',
    'Red Pepper',
    'Sorghum',
    'Soybean',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Ambo Town": [
    'Banana',
    'Garlic',
    'Maize',
    'Malt Barely',
    'Onion',
    'Sorghum',
    'Teff',
    'Tomato',
    'Wheat'
  ],
  "Sheno": ['Banana', 'Malt Barely', 'Onion', 'Teff', 'Wheat'],
  "Obora": ['Banana', 'Maize', 'Malt Barely', 'Potato', 'Teff', 'Wheat'],
  "Mehoni": ['Banana', 'Teff', 'Wheat'],
  "Sire": ['Bean', 'Green Mung', 'Maize', 'Onion', 'Potato', 'Sire', 'Teff', 'Wheat'],
  "Debere Elias Gebeya": ['Teff'],
  "Goleja": ['Banana', 'Potato'],
  "Negelle Arsi": ['Banana', 'Potato', 'Teff'],
  "Tullu Wayu": ['Banana'],
  "Disa ": ['Teff'],
  "Alamata": ['Garlic', 'Maize', 'Onion', 'Potato', 'Red Pepper', 'Sorghum', 'Teff', 'Tomato'],
};
// Crop → Varieties
const Map<String, List<String>> cropNameVarietyMapping = {
  "Teff": ['Mixed Teff', 'Red Teff', 'White Teff'],
  "Maize": ['White Maize'],
  "Wheat": ['White Wheat'],
  "Bean": ['Mixed Bean', 'Red kidney bean', 'White pea bean'],
  "Sesame": ['Mixed Sesame', 'Red Sesame', 'White Sesame'],
  "Onion": ['Onion'],
  "Tomato": ['Tomato'],
  "Avocado": ['Avocado'],
  "Potato": ['Potato'],
  "Garlic": ['Garlic'],
  "Red Pepper": ['Red Pepper'],
  "Banana": ['Raw Bananas', 'Ripe bananas'],
  "Sorghum": ['Sorghum'],
  "Soybean": ['Soybean'],
  "Mango": ['Mango'],
  "Malt Barely": ['Malt Barely'],
  "Local Rice": ['Local Rice'],
  "Green Mung": ['Green Mung'],
  "Pineapple": ['Pineapple'],
};
const List<String> seasons = ["bega", "belg", "kiramit", "tsedey"];