// mappings_pruned.dart

// List of Regions
const List<String> regions = ['Amhara' 'Tigray' 'Oromia' 'South West' 'Sidama' 'SNNP'];

// Region → Zones
const Map<String, List<String>> regionZoneMapping = {
  "Amhara": [
    'South Wollo',
    'Awi Zone',
    'South Gondar',
    'North Wollo',
    'Gonder City Administration',
    'North Gondar',
    'North Shoa',
    'West Gojjam',
    'Wagmera',
    'Dese City Administration',
    'Bahir Dar City Administration',
    'East Gojjam',
    'Central Gondar',
    'Oromia Special',
    'West Gonder'
  ],
  "Tigray": [
    'West Tigray',
    'North Western Tigray',
    'South Tigray',
    'East Tigray',
    'Central Tigray',
    'Mekele Special Zone'
  ],
  "Oromia": [
    'North Shewa',
    'East Harerghe',
    'West Arsi',
    'West Wellega',
    'Jimma',
    'Bale',
    'South West Shewa',
    'Illubabora',
    'Horo Gudru Wellega',
    'East Shewa',
    'West Harerghe',
    'West Shewa',
    'East Wellega',
    'Oromia Special Zone',
    'Arsi',
    'Buno Bedele',
    'Qelem Wellega',
    'East Bale',
    'Borena ',
    'Guji'
  ],
  "South West": [
    'Kefa',
    'Dawuro',
    'Konta',
    'Bench Sheko',
    'Bench Maji',
    'Sheka',
    'West Omo '
  ],
  "Sidama": [
    'Sidama'
  ],
  "SNNP": [
    'Hadiya',
    'Gedeo',
    'Siliti',
    'Gamo',
    'Wolayita',
    'Basketo',
    'Halaba ',
    'Gurage',
    'Kambata',
    'South Omo',
    'Gofa',
    'Yem Special Woreda',
    'Konso'
  ]
};

// Zone → Woredas
const Map<String, List<String>> zoneWoredaMapping = {
  "South Wollo": [
    'Kombolcha Town Administration',
    'Mekane Selam Town Administration',
    'Wereyilu',
    'Tenta',
    'Hayke Town Administration',
    'Legambo',
    'KelalaTown Administration',
    'Albuko',
    'Mehal Saynit',
    'Legehida',
    'Jama'
  ],
  "Awi Zone": [
    'EnjibaraTown Administration',
    'Chageni Town Administration',
    'Dangela Town Administration',
    'Fendika Town Administration',
    'Zigem'
  ],
  "West Tigray": [
    'Humera Town',
    'Welkait'
  ],
  "North Western Tigray": [
    'Tahtay-Koraro',
    'Tahtay-Adiyabo'
  ],
  "South Tigray": [
    'Maychew Town',
    'Raya-Azebo',
    'Raya-Alamata'
  ],
  "East Tigray": [
    'Adigrat',
    'Wukro',
    'Hawzein'
  ],
  "Central Tigray": [
    'Aksum',
    'Kola-Tembeien'
  ],
  "South Gondar": [
    'Mekane Yesus Town Administration',
    'Debretabor Town Administration',
    'Wereta Town Administration',
    'Wegeda Town Administration',
    'Nefas Mewecha Town Administration',
    'Guna Begemedere',
    'Ebinat Town Administration',
    'Dera',
    'Addis Zemen Town Administration'
  ],
"North Wollo": ['Woldiya Town Administration', 'Lalibela Town Administration',
 'Mersa Town Administration', 'Kobo Town Administration'],
"Gonder City Administration": ['Gondar Town  Administration'],
"Mekele Special Zone": ['Mekele Town'],
"North Shewa": ['Fiche City Administration', 'Abichugna', 'Dagam', 'Alaltuu', 'Wuchale',
 'Kimbibit'],
"Kefa": ['Bonga City Administration', 'Chena', 'Gimbo '],
"North Gondar": ['Dabat Town Administration', 'Debark Town Administration'],
"Sidama": ['Aleta Wondo City Administration', 'Hawassa City Administration',
 'Arbigona ', 'Bensa Daye ', 'Boricha', 'Hawassa Zuria ',
 'Yirgalem City Administration ', 'Bona', 'Habe Lalida (Hawala)',
 'Leku City Administration', 'Wondogenet City Administration',
 'Aleta Chuko City Administration', 'Loka Abaya ', 'Wonsho', 'Blate Zuria ',
 'Dara'],
"Hadiya": ['Soro ', 'Badewocho ', 'Hosana City Administration', 'Gombora ', 'Giba ',
 'Shashago '],
"Gedeo": ['Dilla City Administration', 'Gedeb', 'Wonago', 'Kochera', 'Bula ',
 'Yergachefa'],
"East Harerghe": ['Haromaya', 'Deder'],
"Siliti": ['Dalocha', 'Worabe City Administration', 'Sankura ', 'Silte ', 'Hulbareg '],
"Dawuro": ['Gesachere', 'Tercha City Administration', 'Esra', 'Disa '],
"West Arsi": ['Dodola', 'Shashamene City Administration', 'Kofele', 'Heben arsi', 'Kokosa',
 'Adaba', 'Gedeb Asasa', 'Kore', 'Negele Arsi '],
"North Shoa": ['Mehal MedaTown Adminstartion', 'Debere Birhan Town Administration',
 'Debresina Town Administration', 'Alem Ketema Town Administration',
 'Arereti Town Administration', 'Hagere Mariam',
 'Enwari Town Administration', 'Menze Keya Gebreal', 'Asagert',
 'Siya Debirna Wayu', 'Mida Weremo', 'Mojana Wadera',
 'Molale Town Administration'],
"West Gojjam": ['Finote Selam Town Administration', 'Dembecha Town Administration',
 'Merawi Town Administration', 'Bure Town Administration',
 'Adet Town Administration', 'North Achefer', 'Gonje Kolela', 'South Mecha',
 'Durbete Town Administration'],
"West Wellega": ['Najo', 'Gimbi City Administration'],
"Wagmera": ['Sekota Town Administration'],
"Gamo": ['Kutcha ', 'Arbaminch City Administration', 'Deramalo ', 'Kemba Zuria '],
"Jimma": ['Botor Tolay', 'Goma', 'Saka Chokorsa', 'Sokoru', 'Chora Boter', 'Tiro Afata',
 'Omonada', 'Mana', 'Gera', 'Omo Nado', 'Jimma City Administration'],
"Wolayita": ['Areka City Administration', 'Humbo ', 'Sodo City Administration', 'Ufa ',
 ' Duguna Fango ', 'Damot Gale '],
"Konta": ['Konta ', 'Chida Town Administration'],
"Dese City Administration": ['Dese Town Administration'],
"Bench Sheko": ['Mizan City Administration', 'South Bench ', 'Sez Town Administration'],
"Bale": ['Bale Robe City Administration', 'Gasera', 'Goba', 'Dello Menna', 'Dinsho',
 'Agarfa', 'Sinaana', 'Ginir City Administration'],
"South West Shewa": ['Kersa Malima', 'Becho ', 'Goro', 'Ilu', 'Tole', 'Sodo Dache', 'Amaya', 'Weliso',
 'Weliso City Administration'],
"Bahir Dar City Administration": ['Bahir Dar Town  Administration'],
"Illubabora": ['Metu City Administration'],
"Basketo": ['Basketo '],
"Horo Gudru Wellega": ['Shambu City Administration', 'Jima Geneti', 'Horo Buluk', 'Ababoo Guduruu',
 'Jima Rare', 'Guduru', 'Abay Chomen', 'Amuru', 'Abe dongoro'],
"East Shewa": ['Bishoftu  City Administration', 'Dugda', 'Adama City Administration',
 'Modjo City Administration', 'Gido Kombolcha', 'Lome', 'Boset', 'Bora',
 'Liben Chukala'],
"Halaba ": ['Halaba kulito City Administration', 'Atoti Ulo '],
"Gurage": ['Butagira City Administration', 'Cheha ', 'Welkita City Administration',
 'South Sodo ', 'Gunichera City Administration', 'Gumer '],
"Kambata": ['Durame City Administration', 'Hadero Zuria ',
 'Angacha City Administration', 'Kacha Bira ',
 'Doyogena City Administration'],
"East Gojjam": ['Dejen Town Administration', 'Debre Markos Town Administration',
 'BichenaTown Adminstartion', 'Aneded', 'Gunde Woyen Town Administration',
 'Lumame Town Administration', 'Amanuel Town Administration',
 'Debay Tilat Gen', 'Debere Work Town Administration',
 'Mereto LemariamTown Adminstartion', 'Baso Liben', 'Debere Elias'],
"South Omo": ['Ginka City Administration', 'South Ari '],
"Gofa": ['Sawla City Administration', 'Melekoza ', 'Geza Gofa ', 'Uba Debretsehay '],
"Central Gondar": ['Shawra Town Administration', 'Kola Deba Town Administration',
 'Amba Giorgis Town Administration', 'Takusa', 'West Dembia', 'Tach Armacho',
 'Ayekel Town Administration'],
"Yem Special Woreda": ['Yem '],
"Bench Maji": ['Gura-Ferda'],
"Konso": ['Karat City Administration'],
"West Harerghe": ['Habro'],
"West Shewa": ['Ilu Gelan', 'Dendi', 'Ejersa Lafo', 'Jaldu', 'Toke Kutaye', 'Nono',
 'Liban Jawi', 'Ejere', 'Dano', 'Ambo City Administration'],
"East Wellega": ['Sasiga', 'Sibu Sire ', 'Gida Ayana', 'Leka Dulecha', 'Gutoo Gida', 'Diga',
 'Wayu Tuka'],
"Oromia Special": ['Bati Town  Administration', 'Kemise Town Administration'],
"Oromia Special Zone": ['Burayu City Administration', 'Muloo', 'Sulultaa City administration',
 ],
"Arsi": ['Hetosa', 'Limmu Bilbiloo', 'Asella City Administration', 'Munesa', 'Amigna',
 'Shirka', 'Diksis', 'Lode Hexosa', 'Digelu Tijo', 'Honkolo Wabe',
 'Ziway Dugda', 'Sire', 'Tiyo'],
"West Gonder": ['Metema', 'Genda Wuha Town Administration'],
"Buno Bedele": ['Bedele City Administration', 'Borecha', 'Gechi', 'Dabo Hana', 'Chawaka',
 'Didesa'],
"Sheka": ['Masha  ', 'Anderacha '],
"Qelem Wellega": ['Dale Wabara'],
"East Bale": ['Lege Hidha', 'Ginir', 'Gololcha', 'Sawena'],
"Borena ": ['Moyale', 'Yabelo City Administration'],
"West Omo ": ['Meaent Goldiya  ', 'Meaent Shasha '],
"Guji": ['Negele borena City Administration'],
};

// Woreda → Markets
const Map<String, List<String>> woredaMarketMapping = {
  "Kombolcha Town Administration": ['kombolcha kebele 03 Gebeya'],
  "EnjibaraTown Administration": ['Enjbara'],
  "Humera Town": ['Humera'],
  "Tahtay-Koraro": ['Shire-Endaselassie'],
  "Maychew Town": ['Maychew'],
  "Tahtay-Adiyabo": ['Sheraro'],
  "Adigrat": ['Adigrat'],
  "Aksum": ['Aksum'],
  "Mekane Yesus Town Administration": ['Estie Mekane Yesus Gebeya '],
  "Woldiya Town Administration": ['Woldia Gebeya'],
  "Gondar Town  Administration": ['Gondar Kedamie  Gebeya '],
  "Mekele Town": ['Mekele Town'],
  "Fiche City Administration": ['Fiche'],
  "Bonga City Administration": ['Bonga'],
  "Dabat Town Administration": ['Dabat Gebeya'],
  "Aleta Wondo City Administration": ['Aleta wondo'],
  "Soro ": ['Gimbicho'],
  "Dilla City Administration": ['Dilla'],
  "Mekane Selam Town Administration": ['Mekane Selam gebeya'],
  "Haromaya": ['Harar'],
  "Wereyilu": ['Wereyilu Segno Gebeya '],
  "Hawassa City Administration": ['Hawassa '],
  "Dalocha": ['Dalocha'],
  "Gesachere": ['Gesa chere'],
  "Dodola": ['Dodola '],
  "Chena": ['Chena'],
  "Chageni Town Administration": ['Chagini'],
  "Mehal MedaTown Adminstartion": ['Mehal Meda'],
  "Finote Selam Town Administration": ['Fenot selam Gebeya'],
  "Debretabor Town Administration": ['Debretabor Segno Gebeya '],
  "Shashamene City Administration": ['Shashemene Town'],
  "Najo": ['Najo'],
  "Arbigona ": ['Yaye'],
  "Sekota Town Administration": ['Sekota Segno Gebeya'],
  "Kutcha ": ['Selamber'],
  "Botor Tolay": ['Wayu'],
  "Areka City Administration": ['Areka'],
  "Konta ": ['Ameya'],
  "Dese Town Administration": ['Desse Robit Gebaya'],
  "Mizan City Administration": ['Mizan-aman'],
  "Arbaminch City Administration": ['Arbaminchi'],
  "Dembecha Town Administration": ['Dembecha Gebeya'],
  "Debre Birhan Town Administration": ['Debere Birhan Kebele 08 Gebeya'],
  "Merawi Town Administration": ['Merawi Gebeya'],
  "Debark Town Administration": ['Debark Gebeya'],
  "Gimbi City Administration": ['Gimbi Town'],
  "Wereta Town Administration": ['Wereta Arada Gebeya '],
  "Dangela Town Administration": ['Dangla '],
  "Bale Robe City Administration": ['Bale Robe'],
  "Kersa Malima": ['Kersa Malima'],
  "Humbo ": ['Humbo'],
  "Bahir Dar Town  Administration": ['Bahir Dar kebele 04'],
  "Wukro": ['Wukro'],
  "Metu City Administration": ['Metu'],
  "Basketo ": ['Laska'],
  "Shambu City Administration": ['Shambu Town'],
  "Tenta": ['tenta Gebeya'],
  "Bishoftu  City Administration": ['Bishoftu'],
  "Halaba kulito City Administration": ['Halaba'],
  "Debresina Town Administration": ['Debresina Gebeya'],
  "Dugda": ['Meki '],
  "Adama City Administration": ['Adama City'],
  "Badewocho ": ['Shone'],
  "Butagira City Administration": ['Butajira'],
  "Tercha City Administration": ['Tercha'],
  "Cheha ": ['Indebir'],
  "Alem Ketema Town Administration": ['Alem Ketema Kedame Gebeya'],
  "Wegeda Town Administration": ['Wegeda Gebeya'],
  "Lalibela Town Administration": ['Lalibela Ketema Gebeya'],
  "Bensa Daye ": ['Daye'],
  "Durame City Administration": ['Durame'],
  "Hadero Zuria ": ['Hadero'],
  "Sodo City Administration": ['Wolaita Soddo'],
  "Bure Town Administration": ['Bure Woreda'],
  "Welkita City Administration": ['Wolkite'],
  "Dejen Town Administration": ['Dejen Gebeya'],
  "Ginka City Administration": ['Jinka'],
  "Sawla City Administration": ['Sawula'],
  "Shawra Town Administration": ['Shawura Gebeya'],
  "Yem ": ['Saja'],
  "Hosana City Administration": ['Hosaena'],
  "Gura-Ferda": ['Biftu'],
  "Karat City Administration": ['Karat'],
  "Boricha": ['Yirba'],
  "Habro": ['Galamso'],
  "Deder": ['Deder'],
  "Kofele": ['Kofale'],
  "Ilu Gelan": ['Ijaji'],
  "Sasiga": ['Goto 24'],
  "Debre Markos Town Administration": ['Debre Markos Huseta Gebeya'],
  "Welkait": ['Adi-Remets'],
  "Dendi": ['Ginci'],
  "Bati Town  Administration": ['Bati Segno Gebeya'],
  "Kemise Town Administration": ['Kemise Hamus Gebeya '],
  "Burayu City Administration": ['Burayu'],
  "Kola Deba Town Administration": ['Kola Diba'],
  "Modjo City Administration": ['Mojo'],
  "Sibu Sire ": ['Sibusire'],
  "Gida Ayana": ['Gidda Ayana'],
  "Hetosa": ['Itaya'],
  "Gedeb": ['Gedeb'],
  "Worabe City Administration": ['Worabae'],
  "Ejersa Lafo": ['Olonkomi'],
  "Arereti Town Administration": ['Arerti Gebeya '],
  "Gido Kombolcha": ['Batu'],
  "Adet Town Administration": ['Adet Gebeya '],
  "Metema": ['Kokit  Metema Gebeya'],
  "Bedele City Administration": ['Bedele'],
  "Jaldu": ['Gojo'],
  "Becho ": ['Tullo Bolo'],
  "BichenaTown Adminstartion": ['Bichena Gebeya'],
  "Kola-Tembeien": ['Abi-Adi'],
  "Masha  ": ['Masha'],
  "Dale Wabara": ['Kake'],
  "Limmu Bilbiloo": ['Bokoji'],
  "Jima Geneti": ['Harato'],
  "Goma": ['Agaro', 'Goma'],
  "Asella City Administration": ['Asella'],
  "Saka Chokorsa": ['Saka '],
  "Gasera": ['Gasara'],
  "Borecha": ['Yanfa'],
  "Sokoru": ['Sokoru'],
  "Mersa Town Administration": ['Meresa  Gebeya'],
  "Kobo Town Administration": ['Kobo ketema'],
  "Hagere Mariam": ['Shola gebeya'],
  "Hayke Town Administration": ['Hayike'],
  "Enwari Town Administration": ['Enewari'],
  "Legambo": ['Akeseta'],
  "KelalaTown Administration": ['Kelala'],
  "Menze Keya Gebreal": ['Zemereo'],
  "Asagert": ['Ginager'],
  "Siya Debirna Wayu": ['Deneba'],
  "Albuko": ['Salmen'],
  "Mida Weremo": ['Meragna'],
  "Aneded": ['Amber'],
  "South Bench ": ['Debere Work '],
  "North Achefer": ['Liben'],
  "Nefas Mewecha Town Administration": ['Nefas Mewucha'],
  "Amba Giorgis Town Administration": ['Amba Georgies'],
  "Guna Begemedere": ['Kimer Dingay'],
  "Takusa": ['Delgie'],
  "Gunde Woyen Town Administration": ['Gunde woyin'],
  "Ebinat Town Administration": ['Ebenat Ketema'],
  "Lumame Town Administration": ['Lumame'],
  "Gonje Kolela": ['Addis Alem'],
  "Fendika Town Administration": ['Fendika'],
  "West Dembia": ['Chuahit'],
  "Genda Wuha Town Administration": ['Genda wuha'],
  "Mehal Saynit": ['Deansa'],
  "Legehida": ['Weyin Amba'],
  "Amanuel Town Administration": ['Amanuel'],
  "Zigem": ['kelaji'],
  "South Mecha": ['Mehal Genet Gebeya'],
  "Tach Armacho": ['Sanja'],
  "Durbete Town Administration": ['Durbete'],
  "Dera": ['Dera Amebesamie'],
  "Ayekel Town Administration": ['Aykel'],
  "Debay Tilat Gen": ['Kuye'],
  "Debere Work Town Administration": ['Debere Work'],
  "Addis Zemen Town Administration": ['Addis Zemen'],
  "Mojana Wadera": ['Sela dengay'],
  "Molale Town Administration": ['Molalalie'],
  "Jama": ['Degolo'],
  "Horo Buluk": ['Sakele'],
  "Goro": ['Goro South West Shewa'],
  "Ilu": ['Teji'],
  "Leka Dulecha": ['Getema'],
  "Gutoo Gida": ['Uke'],
  "Toke Kutaye": ['Gudar'],
  "Tole": ['Bantu'],
  "Nono": ['Silki Amba'],
  "Diga": ['Ifa'],
  "Ababoo Guduruu": ['Dedu'],
  "Mereto LemariamTown Adminstartion": ['Merto Lemariam'],
  "Lome": ['koka'],
  "Boset": ['walenchiti'],
  "Abichugna": ['Mandida'],
  "Liban Jawi": ['Babicha'],
  "Jima Rare": ['Wayu Jima Rare'],
  "Bora": ['bote'],
  "Sodo Dache": ['Tare'],
  "Muloo": ['Hoja Dure'],
  "Amaya": ['Gindo'],
  "Dagam": ['Hambiso'],
  "Wayu Tuka": ['Gute'],
  "Liben Chukala": ['Adulala'],
  "Weliso": ['Dilela'],
  "Gechi": ['Gechi'],
  "Munesa": ['Kersa'],
  "Heben arsi": ['Goljota'],
  "Amigna": ['Adele'],
  "Shirka": ['Gobesa'],
  "Goba": ['Goba'],
  "Kokosa": ['Kokosaa'],
  "Sulultaa City administration": ['Sululta'],
  "Diksis": ['Hamde'],
  "Dello Menna": ['Menna'],
  "Chora Boter": ['Bagi'],
  "Tiro Afata": ['Dimtu'],
  "Lege Hidha": ['Beltu'],
  "Dabo Hana": ['Kone'],
  "Dinsho": ['Dinsho'],
  "Moyale": ['Moyale'],
  "Chawaka": ['Ilu harer'],
  "Lode Hexosa": ['Huruta'],
  "Alaltuu": ['Mikawa'],
  "Digelu Tijo": ['Sagure'],
  "Agarfa": ['Agarfa'],
  "Ginir": ['Ginir'],
  "Omonada": ['Asandabo'],
  "Adaba": ['Adaba'],
  "Gololcha": ['Jara'],
  "Sawena": ['Micha'],
  "Wuchale": ['Muke turi'],
  "Ejere": ['Addis Alem Ejere'],
  "Gedeb Asasa": ['Asasa'],
  "Mana": ['Yabu'],
  "Gera": ['Chira'],
  "Kore": ['Kore'],
  "Weliso City Administration": ['Weliso Town'],
  "Sez Town Administration": ['Sez'],
  "Sinaana": ['selka'],
  "Dano": ['Sayo'],
  "Meaent Goldiya  ": ['Bachuma '],
  "Meaent Shasha ": ['Jemu '],
  "Wonago": ['Wonago'],
  "Angacha City Administration": ['Angacha '],
  "Sankura ": ['Alemgebaya '],
  "South Sodo ": ['Kela South Sodo'],
  "Melekoza ": ['Laha '],
  "South Ari ": ['Gazer '],
  "Silte ": ['Kibet '],
  "Honkolo Wabe": ['Siltana'],
  "Gunichera City Administration": ['Gunechere'],
  "Kochera": ['Kochera'],
  "Gombora ": ['Habicho '],
  "Bula ": ['Bule'],
  "Yergachefa": ['Yergachefa'],
  "Ufa ": ['Ufa Segno Gebeya'],
  "Giba ": ['Umacho '],
  "Geza Gofa ": ['Dede'],
  "Uba Debretsehay ": ['Zaba'],
  " Duguna Fango ": ['Bitena'],
  "Deramalo ": ['Wacha '],
  "Omo Nado": ['Omo nada'],
  "Hawassa Zuria ": ['Dore'],
  "Yirgalem City Administration ": ['Sedetegna'],
  "Gimbo ": ['Ufa '],
  "Bona": ['Bona 01'],
  "Habe Lalida (Hawala)": ['Haweela'],
  "Shashago ": ['Bonosha '],
  "Kacha Bira ": ['Shinshicho '],
  "Yabelo City Administration": ['Yabello'],
  "Damot Gale ": ['Damot Gale Makesegno Gebeya'],
  "Hulbareg ": ['Kerata '],
  "Leku City Administration": ['Leku '],
  "Wondogenet City Administration": ['Kela'],
  "Baso Liben": ['Yejube'],
  "Kemba Zuria ": ['Kemba '],
  "Atoti Ulo ": ['Guba '],
  "Doyogena City Administration": ['Doyogena '],
  "Gumer ": ['Bole'],
  " Sebeta City Administration": ['Sabata '],
  "Aleta Chuko City Administration": ['Gudumalee'],
  "Anderacha ": ['Gicha'],
  "Esra": ['Esra Bali '],
  "Ginir City Administration": ['Dalo Sebro'],
  "Loka Abaya ": ['Hantate '],
  "Chida Town Administration": ['Chida'],
  "Ziway Dugda": ['Ogolcho'],
  "Negele borena City Administration": ['Negele Borana'],
  "Guduru": ['Kombolcha-wellega'],
  "Wonsho": ['Bokaso'],
  "Didesa": ['Dambi'],
  "Blate Zuria ": ['Balela '],
  "Hawzein": ['Hawzen'],
  "Dara": ['Kawado'],
  "Abay Chomen": ['Finchaha'],
  "Jimma City Administration": ['Jimma Town'],
  "Ambo City Administration": ['Ambo Town'],
  "Kimbibit": ['Sheno'],
  "Amuru": ['Obora'],
  "Raya-Azebo": ['Mehoni'],
  "Sire": ['Sire'],
  "Debere Elias": ['Debere Elias Gebeya'],
  "Tiyo": ['Goleja'],
  "Negele Arsi ": ['Negelle Arsi'],
  "Abe dongoro": ['Tullu Wayu'],
  "Disa ": ['Disa '],
  "Raya-Alamata": ['Alamata'],
};

// Market → Crops
const Map<String, List<String>> marketCropNameMapping = {
  "kombolcha kebele 03 Gebeya": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Garlic', 'Local Rice', 'Sorghum', 'Red Pepper', 'Malt Barely', 'Potato', 'Banana'],
  "Enjbara": ['Maize', 'Teff', 'Wheat', 'Onion', 'Potato', 'Banana'],
  "Humera": ['Teff', 'Wheat'],
  "Shire-Endaselassie": ['Teff', 'Wheat', 'Maize', 'Garlic', 'Onion', 'Potato', 'Tomato', 'Red Pepper', 'Sorghum', 'Banana'],
  "Maychew": ['Maize', 'Teff', 'Sorghum', 'Red Pepper', 'Garlic', 'Onion', 'Potato', 'Tomato', 'Mango', 'Avocado', 'Wheat', 'Banana'],
  "Sheraro": ['Teff', 'Sorghum', 'Maize', 'Onion', 'Garlic', 'Potato', 'Tomato', 'Sesame', 'Wheat', 'Banana'],
  "Adigrat": ['Teff', 'Maize', 'Wheat', 'Red Pepper', 'Garlic', 'Onion', 'Potato', 'Tomato', 'Banana'],
  "Aksum": ['Maize', 'Teff', 'Red Pepper', 'Garlic', 'Onion', 'Potato', 'Tomato', 'Mango', 'Avocado', 'Wheat', 'Sorghum'],
  "Estie Mekane Yesus Gebeya ": ['Maize', 'Wheat', 'Teff'],
  "Woldia Gebeya": ['Maize', 'Teff', 'Wheat'],
  "Gondar Kedamie  Gebeya ": ['Teff', 'Wheat', 'Maize', 'Tomato', 'Onion', 'Potato', 'Avocado', 'Mango', 'Malt Barely', 'Sorghum', 'Red Pepper', 'Banana', 'Garlic', 'Green Mung', 'Local Rice'],
  "Mekele Town": ['Teff', 'Wheat', 'Maize', 'Sorghum', 'Red Pepper', 'Garlic', 'Onion', 'Potato', 'Tomato', 'Mango', 'Avocado', 'Banana'],
  "Fiche": ['Teff', 'Maize', 'Wheat'],
  "Bonga": ['Teff', 'Wheat', 'Maize', 'Tomato', 'Potato', 'Malt Barely', 'Soybean', 'Sorghum', 'Local Rice', 'Garlic', 'Banana', 'Onion'],
  "Dabat Gebeya": ['Teff', 'Maize', 'Wheat', 'Sorghum'],
  "Aleta wondo": ['Teff', 'Maize', 'Wheat', 'Bean', 'Onion', 'Tomato', 'Potato', 'Avocado', 'Garlic', 'Red Pepper', 'Banana'],
  "Gimbicho": ['Teff', 'Wheat', 'Maize', 'Onion', 'Garlic', 'Tomato', 'Potato', 'Avocado', 'Banana', 'Malt Barely', 'Sorghum'],
  "Dilla": ['Maize', 'Teff', 'Wheat', 'Banana', 'Potato', 'Onion', 'Malt Barely'],
  "Mekane Selam gebeya": ['Teff', 'Wheat', 'Maize', 'Mango', 'Banana', 'Potato', 'Onion'],
  "Harar": ['Teff', 'Wheat', 'Maize'],
  "Wereyilu Segno Gebeya ": ['Maize', 'Teff', 'Tomato', 'Potato', 'Onion'],
  "Hawassa ": ['Maize', 'Teff', 'Wheat', 'Banana', 'Onion', 'Tomato', 'Potato', 'Malt Barely', 'Soybean', 'Garlic', 'Red Pepper', 'Sorghum', 'Local Rice', 'Mango', 'Avocado'],
  "Dalocha": ['Teff', 'Wheat', 'Maize', 'Sorghum', 'Red Pepper', 'Malt Barely', 'Local Rice', 'Potato', 'Onion', 'Tomato', 'Mango', 'Avocado', 'Garlic', 'Banana', 'Sesame'],
  "Gesa chere": ['Maize', 'Teff', 'Wheat', 'Malt Barely', 'Sorghum', 'Banana', 'Bean'],
  "Dodola ": ['Maize', 'Teff', 'Wheat', 'Tomato', 'Onion', 'Sorghum', 'Potato', 'Malt Barely', 'Banana', 'Soybean'],
  "Chena": ['Teff', 'Maize', 'Wheat', 'Banana', 'Sorghum', 'Bean', 'Potato', 'Onion', 'Tomato', 'Malt Barely'],
  "Chagini": ['Teff', 'Maize', 'Onion'],
  "Mehal Meda": ['Wheat', 'Maize', 'Teff', 'Onion'],
  "Fenot selam Gebeya": ['Teff', 'Wheat', 'Maize', 'Onion', 'Potato', 'Banana'],
  "Debretabor Segno Gebeya ": ['Teff', 'Maize', 'Wheat', 'Onion', 'Red Pepper', 'Garlic', 'Local Rice', 'Tomato', 'Banana', 'Malt Barely', 'Avocado', 'Mango', 'Potato'],
  "Shashemene Town": ['Teff', 'Wheat', 'Maize', 'Bean', 'Onion', 'Tomato', 'Potato', 'Banana', 'Malt Barely', 'Sorghum', 'Garlic', 'Mango', 'Soybean', 'Avocado', 'Pineapple', 'Red Pepper', 'Local Rice'],
  "Najo": ['Maize', 'Onion', 'Tomato', 'Potato', 'Sorghum', 'Garlic', 'Banana'],
  "Yaye": ['Teff', 'Wheat', 'Maize', 'Malt Barely', 'Potato'],
  "Sekota Segno Gebeya": ['Maize', 'Teff', 'Banana'],
  "Selamber": ['Maize', 'Teff', 'Onion', 'Garlic', 'Soybean', 'Green Mung', 'Wheat', 'Tomato', 'Potato', 'Banana', 'Mango', 'Sorghum', 'Avocado'],
  "Wayu": ['Teff', 'Maize', 'Wheat'],
  "Areka": ['Teff', 'Wheat', 'Maize', 'Onion', 'Bean', 'Tomato', 'Potato', 'Avocado', 'Mango', 'Banana', 'Garlic', 'Red Pepper', 'Pineapple', 'Malt Barely'],
  "Ameya": ['Teff', 'Wheat', 'Maize', 'Onion', 'Avocado', 'Potato', 'Banana', 'Sorghum', 'Malt Barely', 'Tomato', 'Mango', 'Garlic', 'Red Pepper'],
  "Desse Robit Gebaya": ['Teff', 'Wheat', 'Maize', 'Onion', 'Banana', 'Sorghum'],
  "Mizan-aman": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Avocado', 'Banana', 'Garlic', 'Local Rice', 'Mango'],
  "Arbaminchi": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Malt Barely', 'Banana', 'Sorghum', 'Soybean', 'Red Pepper', 'Avocado', 'Mango'],
  "Dembecha Gebeya": ['Teff', 'Wheat', 'Maize', 'Onion'],
  "Debere Birhan Kebele 08 Gebeya": ['Teff', 'Wheat', 'Maize', 'Malt Barely', 'Sorghum', 'Tomato'],
  "Merawi Gebeya": ['Wheat', 'Maize', 'Teff', 'Onion'],
  "Debark Gebeya": ['Teff', 'Maize', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Banana', 'Bean'],
  "Gimbi Town": ['Teff', 'Maize', 'Banana'],
  "Wereta Arada Gebeya ": ['Teff', 'Maize', 'Onion', 'Potato', 'Local Rice', 'Banana', 'Garlic'],
  "Dangla ": ['Teff', 'Maize', 'Potato', 'Malt Barely', 'Wheat'],
  "Bale Robe": ['Teff', 'Wheat', 'Maize', 'Tomato', 'Onion', 'Mango', 'Banana', 'Potato', 'Avocado', 'Malt Barely', 'Sorghum', 'Garlic', 'Red Pepper'],
  "Kersa Malima": ['Teff', 'Wheat', 'Maize', 'Banana'],
  "Humbo": ['Teff', 'Maize', 'Wheat', 'Onion', 'Garlic', 'Avocado', 'Mango', 'Tomato', 'Potato', 'Banana', 'Sorghum', 'Soybean'],
  "Bahir Dar kebele 04": ['Teff', 'Wheat', 'Maize', 'Tomato', 'Onion', 'Potato', 'Banana', 'Local Rice'],
  "Wukro": ['Teff', 'Maize', 'Banana'],
  "Metu": ['Teff', 'Wheat', 'Maize', 'Bean', 'Onion', 'Tomato', 'Potato', 'Banana', 'Malt Barely', 'Sorghum', 'Garlic', 'Red Pepper', 'Local Rice', 'Soybean', 'Avocado', 'Pineapple', 'Mango', 'Sesame'],
  "Laska": ['Teff', 'Maize', 'Wheat', 'Sesame', 'Bean', 'Potato', 'Banana'],
  "Shambu Town": ['Teff', 'Wheat', 'Maize', 'Malt Barely', 'Potato', 'Bean', 'Sorghum', 'Onion', 'Tomato', 'Avocado', 'Garlic'],
  "tenta Gebeya": ['Maize', 'Wheat', 'Sorghum', 'Local Rice', 'Banana'],
  "Bishoftu": ['Maize', 'Tomato', 'Banana', 'Local Rice', 'Bean', 'Malt Barely'],
  "Halaba": ['Teff', 'Wheat', 'Maize', 'Bean', 'Avocado', 'Onion', 'Tomato', 'Potato', 'Sorghum', 'Garlic', 'Soybean', 'Red Pepper', 'Banana', 'Mango', 'Malt Barely', 'Local Rice'],
  "Debresina Gebeya": ['Wheat', 'Maize', 'Teff'],
  "Meki ": ['Teff', 'Wheat', 'Maize', 'Onion', 'Malt Barely', 'Tomato', 'Banana', 'Potato'],
  "Adama City": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Banana', 'Malt Barely', 'Sorghum', 'Local Rice', 'Red Pepper', 'Garlic', 'Mango', 'Soybean', 'Avocado', 'Bean', 'Sesame', 'Pineapple'],
  "Shone": ['Teff', 'Maize', 'Onion', 'Tomato', 'Potato', 'Banana', 'Mango', 'Avocado', 'Red Pepper', 'Garlic'],
  "Butajira": ['Maize', 'Wheat', 'Teff', 'Banana', 'Local Rice', 'Malt Barely', 'Sorghum', 'Soybean', 'Onion', 'Tomato', 'Potato', 'Avocado', 'Mango', 'Garlic', 'Red Pepper', 'Pineapple', 'Bean'],
  "Tercha": ['Teff', 'Wheat', 'Maize', 'Bean', 'Tomato', 'Potato', 'Avocado', 'Mango', 'Banana', 'Sorghum', 'Garlic', 'Red Pepper', 'Malt Barely', 'Onion', 'Soybean', 'Local Rice', 'Pineapple'],
  "Indebir": ['Teff', 'Wheat', 'Maize', 'Tomato', 'Potato', 'Avocado', 'Onion', 'Banana', 'Garlic', 'Mango'],
  "Alem Ketema Kedame Gebeya": ['Maize', 'Teff', 'Tomato'],
  "Wegeda Gebeya": ['Teff', 'Maize', 'Banana'],
  "Lalibela Ketema Gebeya": ['Teff', 'Wheat', 'Maize', 'Sorghum'],
  "Daye": ['Teff', 'Maize', 'Wheat', 'Bean', 'Malt Barely', 'Local Rice', 'Onion', 'Tomato', 'Potato', 'Garlic', 'Soybean', 'Avocado'],
  "Durame": ['Maize', 'Teff', 'Wheat', 'Bean', 'Tomato', 'Potato', 'Garlic', 'Onion', 'Banana'],
  "Hadero": ['Bean', 'Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Avocado', 'Potato', 'Mango', 'Banana'],
  "Wolaita Soddo": ['Teff', 'Wheat', 'Maize', 'Onion', 'Potato', 'Tomato', 'Garlic', 'Banana', 'Sorghum', 'Green Mung'],
  "Bure Woreda": ['Wheat', 'Maize', 'Banana'],
  "Wolkite": ['Teff', 'Maize', 'Garlic', 'Onion', 'Tomato'],
  "Dejen Gebeya": ['Wheat', 'Maize', 'Teff', 'Potato'],
  "Jinka": ['Teff', 'Wheat', 'Maize', 'Garlic', 'Tomato', 'Onion', 'Potato', 'Banana', 'Bean', 'Sorghum'],
  "Sawula": ['Maize', 'Teff', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Banana', 'Garlic', 'Local Rice', 'Sorghum', 'Soybean', 'Red Pepper', 'Green Mung', 'Avocado', 'Mango', 'Malt Barely', 'Bean', 'Sesame'],
  "Shawura Gebeya": ['Teff', 'Maize', 'Sesame', 'Onion', 'Potato', 'Banana', 'Garlic', 'Sorghum', 'Tomato', 'Red Pepper'],
  "Saja": ['Wheat', 'Maize', 'Teff', 'Banana'],
  "Hosaena": ['Teff', 'Wheat', 'Maize', 'Sorghum', 'Tomato', 'Avocado', 'Onion', 'Mango', 'Garlic', 'Potato', 'Red Pepper', 'Banana', 'Malt Barely', 'Pineapple', 'Local Rice'],
  "Biftu": ['Teff', 'Wheat', 'Maize', 'Sesame', 'Bean', 'Onion', 'Tomato', 'Sorghum'],
  "Karat": ['Teff', 'Maize', 'Wheat', 'Sesame', 'Bean', 'Garlic', 'Red Pepper', 'Local Rice', 'Soybean', 'Onion', 'Avocado', 'Tomato', 'Potato', 'Banana', 'Malt Barely', 'Mango', 'Sorghum', 'Green Mung'],
  "Yirba": ['Teff', 'Maize', 'Wheat', 'Avocado', 'Potato', 'Onion', 'Tomato', 'Bean'],
  "Galamso": ['Maize', 'Bean', 'Teff', 'Wheat', 'Onion', 'Tomato', 'Sorghum', 'Malt Barely', 'Garlic', 'Red Pepper', 'Potato', 'Soybean', 'Banana', 'Local Rice'],
  "Deder": ['Maize', 'Banana', 'Teff', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Garlic', 'Malt Barely', 'Sorghum', 'Local Rice'],
  "Kofale": ['Maize', 'Teff', 'Wheat', 'Malt Barely', 'Potato', 'Banana'],
  "Ijaji": ['Teff', 'Maize', 'Banana'],
  "Goto 24": ['Sesame', 'Maize', 'Teff', 'Onion', 'Sorghum', 'Banana', 'Bean'],
  "Debre Markos Huseta Gebeya": ['Teff', 'Banana'],
  "Adi-Remets": ['Teff'],
  "Ginci": ['Wheat', 'Teff', 'Onion', 'Tomato', 'Malt Barely', 'Garlic', 'Maize'],
  "Bati Segno Gebeya": ['Teff', 'Maize', 'Banana'],
  "Kemise Hamus Gebeya ": ['Teff', 'Maize', 'Potato', 'Onion', 'Garlic', 'Mango', 'Local Rice', 'Banana', 'Avocado', 'Sorghum'],
  "Burayu": ['Teff', 'Wheat', 'Maize', 'Malt Barely', 'Sorghum', 'Local Rice', 'Tomato', 'Mango', 'Sesame', 'Onion', 'Potato', 'Banana', 'Soybean', 'Garlic', 'Avocado', 'Red Pepper', 'Bean'],
  "Kola Diba": ['Maize', 'Teff', 'Banana'],
  "Mojo": ['Teff', 'Onion', 'Tomato', 'Potato', 'Garlic', 'Red Pepper', 'Local Rice', 'Wheat', 'Maize', 'Banana', 'Bean', 'Malt Barely', 'Sorghum', 'Mango'],
  "Sibusire": ['Maize', 'Banana', 'Teff'],
  "Gidda Ayana": ['Teff'],
  "Itaya": ['Maize', 'Sorghum', 'Teff', 'Wheat'],
  "Gedeb": ['Bean', 'Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Soybean', 'Garlic'],
  "Worabae": ['Teff', 'Wheat', 'Maize', 'Garlic', 'Potato', 'Tomato', 'Avocado', 'Red Pepper', 'Onion', 'Mango', 'Soybean', 'Banana', 'Local Rice', 'Sorghum', 'Pineapple'],
  "Olonkomi": ['Teff', 'Wheat', 'Banana', 'Tomato', 'Potato'],
  "Arerti Gebeya ": ['Teff', 'Wheat'],
  "Batu": ['Wheat', 'Maize', 'Teff', 'Bean', 'Onion', 'Tomato', 'Garlic', 'Potato', 'Malt Barely', 'Sorghum', 'Red Pepper', 'Soybean', 'Local Rice', 'Avocado'],
  "Adet Gebeya ": ['Teff', 'Onion'],
  "Kokit  Metema Gebeya": ['Teff', 'Banana'],
  "Bedele": ['Teff', 'Maize', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Banana', 'Malt Barely', 'Sorghum', 'Local Rice', 'Garlic', 'Red Pepper', 'Mango'],
  "Gojo": ['Maize', 'Banana'],
  "Tullo Bolo": ['Teff', 'Tomato', 'Banana'],
  "Bichena Gebeya": ['Teff', 'Onion', 'Garlic'],
  "Abi-Adi": ['Teff'],
  "Masha": ['Teff', 'Maize', 'Avocado', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Mango', 'Banana', 'Sorghum', 'Local Rice', 'Garlic', 'Red Pepper', 'Sesame', 'Bean', 'Malt Barely'],
  "Kake": ['Teff', 'Bean', 'Wheat', 'Maize'],
  "Bokoji": ['Wheat', 'Maize'],
  "Harato": ['Teff', 'Banana'],
  "Agaro": ['Onion', 'Tomato', 'Banana', 'Teff', 'Wheat', 'Maize', 'Malt Barely', 'Sorghum', 'Local Rice', 'Soybean', 'Potato', 'Avocado', 'Mango', 'Garlic', 'Red Pepper'],
  "Asella": ['Onion', 'Banana'],
  "Saka ": ['Wheat', 'Maize', 'Avocado', 'Banana', 'Green Mung', 'Mango', 'Teff', 'Onion', 'Potato', 'Garlic', 'Tomato', 'Sorghum', 'Malt Barely'],
  "Gasara": ['Onion', 'Wheat', 'Potato', 'Teff'],
  "Yanfa": ['Tomato'],
  "Sokoru": ['Onion'],
  "Meresa  Gebeya": ['Teff', 'Red Pepper'],
  "Kobo ketema": ['Teff', 'Wheat', 'Red Pepper', 'Banana', 'Garlic'],
  "Shola gebeya": ['Teff', 'Wheat'],
  "Hayike": ['Teff', 'Maize', 'Onion', 'Tomato', 'Banana', 'Red Pepper', 'Green Mung', 'Garlic', 'Sorghum', 'Mango', 'Potato', 'Wheat'],
  "Enewari": ['Teff'],
  "Akeseta": ['Teff'],
  "Kelala": ['Teff', 'Bean', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Sorghum', 'Banana', 'Red Pepper'],
  "Zemereo": ['Teff', 'Wheat', 'Maize'],
  "Ginager": ['Teff', 'Maize', 'Onion', 'Tomato', 'Wheat'],
  "Deneba": ['Teff'],
  "Salmen": ['Teff', 'Wheat', 'Onion', 'Red Pepper'],
  "Meragna": ['Tomato', 'Onion', 'Wheat', 'Potato', 'Maize', 'Red Pepper', 'Teff'],
  "Amber": ['Teff'],
  "Debere Work ": ['Teff', 'Avocado', 'Banana', 'Maize', 'Mango', 'Tomato', 'Potato', 'Garlic', 'Onion'],
  "Liben": ['Teff'],
  "Nefas Mewucha": ['Teff', 'Tomato', 'Garlic', 'Red Pepper', 'Maize', 'Wheat', 'Onion', 'Potato', 'Sorghum', 'Malt Barely', 'Local Rice', 'Banana', 'Bean', 'Mango', 'Avocado'],
  "Amba Georgies": ['Teff', 'Onion', 'Potato', 'Banana', 'Tomato'],
  "Kimer Dingay": ['Teff', 'Wheat', 'Maize', 'Banana'],
  "Delgie": ['Teff', 'Potato', 'Banana', 'Onion'],
  "Gunde woyin": ['Teff', 'Wheat', 'Maize', 'Soybean', 'Red Pepper', 'Banana', 'Sesame', 'Onion'],
  "Ebenat Ketema": ['Teff', 'Maize', 'Wheat', 'Red Pepper', 'Banana'],
  "Lumame": ['Teff', 'Wheat', 'Sorghum', 'Onion', 'Maize', 'Red Pepper', 'Tomato'],
  "Addis Alem": ['Teff', 'Mango'],
  "Fendika": ['Teff', 'Onion', 'Potato', 'Sorghum', 'Tomato', 'Maize', 'Banana', 'Soybean'],
  "Chuahit": ['Teff', 'Potato', 'Sorghum', 'Onion', 'Banana', 'Maize', 'Tomato', 'Garlic'],
  "Genda wuha": ['Teff', 'Onion', 'Potato', 'Tomato'],
  "Deansa": ['Teff', 'Maize', 'Potato', 'Onion', 'Wheat'],
  "Weyin Amba": ['Teff', 'Banana'],
  "Amanuel": ['Teff'],
  "kelaji": ['Teff', 'Red Pepper', 'Maize', 'Onion'],
  "Mehal Genet Gebeya": ['Teff', 'Maize', 'Onion', 'Potato', 'Sesame'],
  "Sanja": ['Teff', 'Maize', 'Banana'],
  "Durbete": ['Teff', 'Onion', 'Potato', 'Garlic', 'Tomato', 'Local Rice', 'Banana', 'Maize'],
  "Dera Amebesamie": ['Teff', 'Wheat', 'Maize', 'Banana'],
  "Aykel": ['Teff'],
  "Kuye": ['Teff', 'Maize', 'Onion', 'Red Pepper'],
  "Debere Work": ['Teff', 'Maize', 'Wheat', 'Soybean'],
  "Addis Zemen": ['Maize', 'Garlic', 'Onion', 'Potato', 'Tomato', 'Teff'],
  "Sela dengay": ['Wheat', 'Teff'],
  "Molalalie": ['Maize', 'Teff'],
  "Degolo": ['Maize', 'Onion', 'Tomato', 'Potato', 'Local Rice', 'Red Pepper'],
  "Sakele": ['Teff', 'Wheat', 'Maize', 'Malt Barely', 'Soybean', 'Potato'],
  "Goro South West Shewa": ['Teff', 'Maize', 'Red Pepper', 'Banana'],
  "Teji": ['Teff', 'Maize', 'Onion', 'Wheat', 'Tomato', 'Banana', 'Garlic', 'Potato'],
  "Getema": ['Maize', 'Bean', 'Wheat', 'Tomato', 'Teff', 'Onion', 'Sesame', 'Potato', 'Banana', 'Sorghum', 'Garlic', 'Red Pepper', 'Malt Barely'],
  "Uke": ['Maize', 'Wheat', 'Onion', 'Tomato', 'Sorghum', 'Teff', 'Sesame', 'Banana', 'Mango'],
  "Gudar": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Malt Barely', 'Garlic', 'Sorghum', 'Red Pepper', 'Banana'],
  "Bantu": ['Tomato', 'Wheat', 'Maize', 'Teff', 'Malt Barely', 'Onion', 'Potato', 'Banana', 'Garlic', 'Red Pepper'],
  "Silki Amba": ['Teff', 'Maize', 'Onion', 'Tomato', 'Potato', 'Red Pepper', 'Garlic', 'Sorghum', 'Wheat', 'Banana', 'Bean'],
  "Ifa": ['Onion', 'Tomato', 'Wheat', 'Teff', 'Maize', 'Sesame', 'Potato', 'Avocado', 'Banana', 'Malt Barely', 'Sorghum', 'Garlic', 'Mango', 'Local Rice', 'Bean', 'Red Pepper'],
  "Dedu": ['Sesame', 'Maize', 'Teff', 'Wheat', 'Banana'],
  "Merto Lemariam": ['Maize', 'Garlic', 'Tomato', 'Red Pepper', 'Local Rice'],
  "koka": ['Teff', 'Maize', 'Wheat', 'Potato', 'Local Rice', 'Red Pepper', 'Banana', 'Malt Barely', 'Sorghum', 'Garlic', 'Tomato'],
  "walenchiti": ['Teff', 'Wheat', 'Malt Barely', 'Garlic', 'Maize', 'Sorghum', 'Tomato', 'Onion', 'Bean'],
  "Mandida": ['Wheat', 'Maize', 'Sesame', 'Onion', 'Tomato', 'Potato', 'Banana', 'Sorghum', 'Garlic', 'Red Pepper', 'Teff', 'Malt Barely'],
  "Babicha": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Malt Barely', 'Garlic', 'Red Pepper', 'Sorghum', 'Banana'],
  "Wayu Jima Rare": ['Maize', 'Wheat', 'Teff', 'Onion', 'Tomato', 'Potato', 'Malt Barely', 'Sorghum', 'Garlic', 'Red Pepper'],
  "bote": ['Wheat', 'Teff', 'Tomato', 'Maize', 'Malt Barely', 'Local Rice', 'Garlic', 'Red Pepper', 'Banana', 'Onion', 'Potato', 'Bean'],
  "Tare": ['Onion', 'Teff', 'Sesame', 'Wheat', 'Maize', 'Tomato', 'Potato', 'Garlic', 'Soybean', 'Red Pepper', 'Malt Barely', 'Banana'],
  "Hoja Dure": ['Teff', 'Banana'],
  "Gindo": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Red Pepper', 'Malt Barely', 'Sorghum', 'Garlic', 'Banana'],
  "Hambiso": ['Teff', 'Maize', 'Onion', 'Tomato', 'Banana'],
  "Gute": ['Teff', 'Maize', 'Red Pepper', 'Banana'],
  "Adulala": ['Teff', 'Wheat', 'Onion', 'Tomato', 'Soybean', 'Maize', 'Malt Barely', 'Banana', 'Bean'],
  "Dilela": ['Maize', 'Teff', 'Wheat', 'Onion', 'Tomato', 'Malt Barely', 'Garlic', 'Potato', 'Sorghum'],
  "Gechi": ['Teff', 'Wheat', 'Maize', 'Bean', 'Onion', 'Tomato', 'Malt Barely', 'Sorghum', 'Potato', 'Green Mung', 'Banana'],
  "Kersa": ['Onion', 'Wheat', 'Maize', 'Teff', 'Tomato', 'Potato', 'Malt Barely', 'Red Pepper', 'Bean', 'Sorghum', 'Garlic', 'Soybean', 'Banana'],
  "Goljota": ['Wheat', 'Teff', 'Maize', 'Potato', 'Onion', 'Tomato', 'Avocado', 'Mango', 'Garlic', 'Malt Barely', 'Local Rice', 'Soybean', 'Red Pepper', 'Banana'],
  "Adele": ['Wheat', 'Teff', 'Maize', 'Onion', 'Tomato', 'Red Pepper', 'Banana', 'Malt Barely'],
  "Gobesa": ['Wheat', 'Teff', 'Maize', 'Potato', 'Onion', 'Tomato', 'Banana', 'Malt Barely', 'Red Pepper', 'Sorghum', 'Garlic', 'Mango'],
  "Goba": ['Teff', 'Wheat', 'Onion', 'Tomato', 'Banana', 'Sesame', 'Maize', 'Soybean', 'Sorghum', 'Red Pepper', 'Garlic', 'Potato'],
  "Kokosaa": ['Teff', 'Maize', 'Bean', 'Wheat', 'Onion', 'Tomato', 'Banana', 'Malt Barely', 'Potato'],
  "Sululta": ['Wheat', 'Onion', 'Teff', 'Tomato', 'Potato', 'Garlic', 'Banana', 'Bean'],
  "Hamde": ['Wheat', 'Teff', 'Maize', 'Tomato', 'Sesame', 'Onion', 'Malt Barely', 'Sorghum', 'Garlic', 'Red Pepper', 'Potato', 'Banana', 'Soybean', 'Local Rice'],
  "Menna": ['Wheat', 'Maize', 'Onion', 'Bean', 'Teff', 'Tomato', 'Potato', 'Malt Barely', 'Garlic', 'Sorghum', 'Mango', 'Red Pepper', 'Green Mung', 'Banana'],
  "Bagi": ['Teff', 'Wheat', 'Maize', 'Sesame', 'Bean', 'Onion', 'Malt Barely', 'Tomato', 'Banana'],
  "Dimtu": ['Wheat', 'Teff', 'Maize', 'Onion', 'Tomato', 'Red Pepper', 'Garlic', 'Potato', 'Mango', 'Avocado', 'Banana'],
  "Beltu": ['Teff', 'Wheat', 'Maize', 'Sesame', 'Mango', 'Red Pepper', 'Potato', 'Banana', 'Tomato', 'Sorghum', 'Green Mung', 'Bean', 'Onion', 'Malt Barely'],
  "Kone": ['Maize', 'Onion', 'Tomato', 'Teff', 'Wheat', 'Red Pepper', 'Potato', 'Sorghum', 'Malt Barely', 'Garlic', 'Bean', 'Mango', 'Banana', 'Sesame', 'Soybean', 'Avocado'],
  "Dinsho": ['Maize', 'Wheat', 'Teff', 'Potato', 'Malt Barely', 'Garlic', 'Banana', 'Soybean'],
  "Moyale": ['Teff', 'Maize', 'Onion', 'Bean', 'Tomato', 'Potato', 'Malt Barely', 'Avocado', 'Mango', 'Banana', 'Wheat', 'Red Pepper', 'Local Rice'],
  "Ilu harer": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Banana', 'Sorghum', 'Local Rice', 'Soybean', 'Garlic', 'Bean', 'Malt Barely', 'Mango'],
  "Huruta": ['Wheat', 'Teff', 'Onion', 'Tomato', 'Malt Barely', 'Maize', 'Red Pepper', 'Potato', 'Banana', 'Garlic'],
  "Mikawa": ['Teff', 'Wheat', 'Malt Barely', 'Banana', 'Maize'],
  "Sagure": ['Teff', 'Wheat', 'Malt Barely', 'Garlic', 'Maize', 'Sorghum', 'Soybean', 'Onion', 'Potato', 'Tomato', 'Red Pepper', 'Banana', 'Bean', 'Avocado'],
  "Agarfa": ['Teff', 'Maize', 'Wheat', 'Onion', 'Red Pepper', 'Malt Barely', 'Tomato', 'Potato', 'Avocado', 'Banana', 'Sorghum', 'Green Mung', 'Garlic', 'Mango'],
  "Ginir": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Malt Barely', 'Garlic', 'Soybean', 'Red Pepper', 'Potato', 'Banana', 'Green Mung', 'Mango', 'Sorghum'],
  "Asandabo": ['Teff', 'Onion', 'Tomato', 'Garlic', 'Banana', 'Potato', 'Red Pepper'],
  "Adaba": ['Teff', 'Tomato', 'Onion', 'Potato', 'Banana', 'Malt Barely', 'Garlic', 'Red Pepper', 'Wheat'],
  "Jara": ['Teff', 'Maize', 'Onion', 'Wheat', 'Garlic', 'Potato', 'Tomato', 'Red Pepper', 'Banana', 'Mango', 'Sorghum', 'Bean', 'Avocado'],
  "Micha": ['Teff', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Banana', 'Sorghum', 'Maize', 'Mango'],
  "Muke turi": ['Teff', 'Wheat', 'Onion', 'Tomato', 'Maize', 'Malt Barely', 'Potato', 'Sorghum', 'Banana'],
  "Addis Alem Ejere": ['Teff', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Garlic', 'Malt Barely', 'Maize', 'Sorghum'],
  "Asasa": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Avocado', 'Banana', 'Malt Barely', 'Sorghum', 'Garlic', 'Soybean', 'Red Pepper'],
  "Yabu": ['Teff', 'Maize', 'Sesame', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Avocado', 'Malt Barely', 'Banana', 'Sorghum', 'Local Rice', 'Garlic', 'Mango', 'Red Pepper'],
  "Chira": ['Teff', 'Maize', 'Wheat', 'Tomato', 'Sorghum', 'Onion', 'Garlic', 'Potato', 'Avocado'],
  "Kore": ['Teff', 'Potato', 'Malt Barely', 'Soybean', 'Garlic', 'Maize', 'Wheat', 'Onion', 'Tomato', 'Banana'],
  "Weliso Town": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Malt Barely', 'Banana', 'Sorghum', 'Garlic', 'Red Pepper', 'Mango', 'Avocado', 'Pineapple'],
  "Goma": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Local Rice', 'Potato', 'Sorghum', 'Banana', 'Garlic', 'Red Pepper', 'Mango', 'Bean'],
  "Sez": ['Teff', 'Maize', 'Potato', 'Sorghum', 'Local Rice', 'Red Pepper', 'Bean', 'Onion', 'Tomato', 'Banana', 'Malt Barely', 'Soybean', 'Garlic', 'Wheat', 'Sesame'],
  "selka": ['Teff', 'Malt Barely', 'Wheat', 'Red Pepper', 'Sorghum', 'Onion', 'Tomato', 'Banana'],
  "Sayo": ['Red Pepper', 'Teff', 'Maize', 'Sorghum', 'Onion', 'Tomato', 'Potato', 'Garlic', 'Banana'],
  "Bachuma ": ['Maize', 'Sorghum', 'Bean', 'Potato', 'Red Pepper', 'Teff', 'Sesame', 'Onion', 'Garlic', 'Local Rice', 'Tomato', 'Avocado', 'Mango'],
  "Jemu ": ['Sesame', 'Banana', 'Sorghum', 'Bean', 'Teff', 'Maize', 'Malt Barely', 'Potato', 'Tomato', 'Onion', 'Garlic', 'Local Rice', 'Avocado', 'Red Pepper'],
  "Wonago": ['Wheat', 'Teff', 'Mango', 'Banana', 'Tomato', 'Maize', 'Potato', 'Onion', 'Avocado', 'Garlic', 'Bean'],
  "Angacha ": ['Teff', 'Maize', 'Wheat', 'Sorghum', 'Tomato'],
  "Alemgebaya ": ['Teff', 'Banana', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Red Pepper', 'Potato', 'Bean'],
  "Kela South Sodo": ['Teff', 'Sorghum', 'Onion', 'Tomato', 'Wheat', 'Maize', 'Potato', 'Malt Barely', 'Garlic', 'Local Rice', 'Red Pepper', 'Avocado', 'Banana', 'Mango', 'Pineapple'],
  "Laha ": ['Green Mung', 'Maize', 'Onion', 'Tomato', 'Teff', 'Wheat', 'Malt Barely', 'Mango', 'Avocado', 'Potato', 'Local Rice'],
  "Gazer ": ['Maize', 'Wheat', 'Teff', 'Onion', 'Banana', 'Tomato', 'Avocado', 'Mango', 'Malt Barely', 'Sorghum', 'Garlic', 'Potato', 'Local Rice', 'Bean'],
  "Kibet ": ['Teff', 'Banana', 'Maize', 'Wheat', 'Onion', 'Tomato', 'Potato', 'Bean'],
  "Siltana": ['Sorghum', 'Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Malt Barely', 'Red Pepper', 'Potato', 'Banana'],
  "Gunechere": ['Teff', 'Onion', 'Tomato', 'Avocado', 'Potato', 'Local Rice', 'Maize', 'Wheat'],
  "Kochera": ['Garlic', 'Potato', 'Tomato', 'Red Pepper', 'Banana', 'Teff'],
  "Habicho ": ['Wheat', 'Teff', 'Banana', 'Maize', 'Malt Barely', 'Sorghum', 'Bean'],
  "Bule": ['Teff', 'Sesame'],
  "Yergachefa": ['Wheat', 'Tomato', 'Avocado', 'Potato', 'Teff', 'Maize', 'Garlic', 'Bean', 'Onion', 'Malt Barely', 'Local Rice', 'Red Pepper', 'Sorghum', 'Sesame'],
  "Ufa Segno Gebeya": ['Teff', 'Avocado', 'Maize', 'Tomato', 'Banana', 'Bean', 'Soybean', 'Local Rice', 'Wheat', 'Onion', 'Potato', 'Sorghum', 'Garlic', 'Red Pepper', 'Mango'],
  "Umacho ": ['Teff', 'Wheat', 'Maize', 'Potato', 'Sorghum', 'Tomato', 'Banana', 'Avocado', 'Onion', 'Green Mung', 'Mango'],
  "Dede": ['Tomato', 'Teff', 'Wheat', 'Maize', 'Malt Barely', 'Bean', 'Onion', 'Avocado', 'Banana', 'Potato', 'Garlic', 'Green Mung'],
  "Zaba": ['Maize', 'Teff', 'Malt Barely', 'Garlic', 'Wheat', 'Sorghum', 'Onion', 'Tomato', 'Potato', 'Banana'],
  "Bitena": ['Teff', 'Maize', 'Banana', 'Wheat', 'Bean', 'Onion', 'Avocado', 'Malt Barely', 'Local Rice'],
  "Wacha ": ['Teff', 'Banana', 'Maize'],
  "Omo nada": ['Tomato', 'Potato', 'Garlic', 'Onion'],
  "Dore": ['Wheat', 'Mango', 'Tomato', 'Potato', 'Red Pepper', 'Garlic', 'Avocado', 'Maize', 'Onion', 'Teff', 'Bean', 'Banana'],
  "Sedetegna": ['Wheat', 'Teff', 'Potato', 'Maize', 'Red Pepper', 'Garlic', 'Onion', 'Avocado', 'Bean', 'Tomato', 'Banana', 'Mango', 'Soybean'],
  "Ufa ": ['Potato', 'Teff', 'Maize', 'Wheat'],
  "Bona 01": ['Potato', 'Onion', 'Teff', 'Wheat', 'Maize', 'Malt Barely', 'Tomato', 'Garlic', 'Bean', 'Soybean'],
  "Haweela": ['Potato', 'Avocado', 'Maize', 'Teff', 'Onion', 'Garlic', 'Banana', 'Tomato', 'Bean', 'Soybean', 'Wheat', 'Local Rice', 'Red Pepper'],
  "Bonosha ": ['Teff', 'Maize', 'Wheat', 'Red Pepper', 'Tomato', 'Sorghum', 'Banana', 'Potato', 'Bean'],
  "Shinshicho ": ['Teff', 'Wheat', 'Bean', 'Potato', 'Avocado', 'Onion', 'Tomato', 'Mango', 'Banana', 'Garlic', 'Sorghum', 'Soybean', 'Maize', 'Red Pepper', 'Malt Barely', 'Local Rice'],
  "Yabello": ['Onion', 'Tomato', 'Potato', 'Teff', 'Bean', 'Maize', 'Garlic', 'Banana', 'Wheat', 'Malt Barely'],
  "Damot Gale Makesegno Gebeya": ['Teff', 'Wheat', 'Maize', 'Potato'],
  "Kerata ": ['Teff', 'Wheat', 'Maize', 'Sorghum', 'Tomato', 'Onion', 'Potato'],
  "Leku ": ['Teff', 'Maize', 'Onion', 'Tomato', 'Potato', 'Banana', 'Malt Barely', 'Garlic', 'Red Pepper', 'Avocado', 'Bean'],
  "Kela": ['Wheat', 'Teff', 'Maize', 'Bean', 'Onion', 'Tomato', 'Potato', 'Avocado', 'Mango', 'Banana', 'Local Rice', 'Garlic', 'Soybean', 'Red Pepper', 'Malt Barely'],
  "Yejube": ['Teff'],
  "Kemba ": ['Banana', 'Teff', 'Maize', 'Mango', 'Tomato', 'Onion', 'Sorghum', 'Wheat', 'Potato', 'Avocado'],
  "Guba ": ['Teff', 'Wheat', 'Maize', 'Sorghum', 'Red Pepper', 'Bean', 'Potato', 'Garlic', 'Soybean'],
  "Doyogena ": ['Banana', 'Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Malt Barely', 'Avocado', 'Garlic'],
  "Bole": ['Banana', 'Local Rice'],
  "Sabata ": ['Onion', 'Tomato', 'Banana', 'Maize'],
  "Gudumalee": ['Banana', 'Wheat', 'Local Rice', 'Bean', 'Maize'],
  "Gicha": ['Banana'],
  "Esra Bali ": ['Banana'],
  "Dalo Sebro": ['Wheat', 'Maize', 'Onion', 'Potato', 'Mango', 'Banana', 'Sorghum', 'Local Rice', 'Tomato', 'Garlic', 'Red Pepper', 'Malt Barely', 'Teff', 'Avocado', 'Pineapple'],
  "Hantate ": ['Teff', 'Wheat', 'Onion', 'Potato', 'Red Pepper', 'Garlic', 'Maize', 'Tomato', 'Bean'],
  "Chida": ['Teff', 'Maize', 'Sorghum', 'Onion', 'Wheat', 'Red Pepper'],
  "Ogolcho": ['Teff', 'Garlic', 'Maize', 'Tomato', 'Wheat', 'Potato', 'Bean', 'Malt Barely', 'Onion', 'Red Pepper', 'Banana'],
  "Negele Borana": ['Teff', 'Potato', 'Onion', 'Wheat', 'Soybean', 'Malt Barely'],
  "Kombolcha-wellega": ['Sorghum', 'Teff'],
  "Bokaso": ['Teff', 'Wheat', 'Maize', 'Onion', 'Garlic', 'Tomato', 'Potato', 'Local Rice', 'Malt Barely'],
  "Dambi": ['Red Pepper', 'Onion'],
  "Balela ": ['Maize', 'Teff', 'Malt Barely', 'Local Rice', 'Red Pepper', 'Bean', 'Onion', 'Sesame', 'Garlic', 'Tomato', 'Soybean', 'Potato', 'Wheat'],
  "Hawzen": ['Teff', 'Wheat', 'Maize', 'Banana'],
  "Kawado": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Potato', 'Avocado', 'Banana', 'Malt Barely', 'Garlic', 'Red Pepper', 'Mango', 'Local Rice'],
  "Finchaha": ['Onion', 'Banana'],
  "Jimma Town": ['Wheat', 'Teff', 'Maize', 'Onion', 'Tomato', 'Potato', 'Banana', 'Malt Barely', 'Sorghum', 'Local Rice', 'Garlic', 'Soybean', 'Red Pepper', 'Avocado', 'Pineapple', 'Mango'],
  "Ambo Town": ['Teff', 'Wheat', 'Maize', 'Onion', 'Tomato', 'Malt Barely', 'Garlic', 'Sorghum', 'Banana'],
  "Sheno": ['Teff', 'Wheat', 'Malt Barely', 'Banana', 'Onion'],
  "Obora": ['Teff', 'Wheat', 'Maize', 'Potato', 'Malt Barely', 'Banana'],
  "Mehoni": ['Wheat', 'Teff', 'Banana'],
  "Sire": ['Teff', 'Wheat', 'Maize', 'Potato', 'Green Mung', 'Bean', 'Onion'],
  "Debere Elias Gebeya": ['Teff'],
  "Goleja": ['Banana', 'Potato'],
  "Negelle Arsi": ['Banana', 'Teff', 'Potato'],
  "Tullu Wayu": ['Banana'],
  "Disa ": ['Teff'],
  "Alamata": ['Sorghum', 'Teff', 'Maize', 'Potato', 'Tomato', 'Onion', 'Garlic', 'Red Pepper'],
};

// Crop → Varieties
const Map<String, List<String>> cropNameVarietyMapping = {
  "Teff": ['Mixed Teff', 'White Teff', 'Red Teff'],
  "Maize": ['White Maize'],
  "Wheat": ['White Wheat'],
  "Bean": ['White pea bean', 'Red kidney bean', 'Mixed Bean'],
  "Sesame": ['White Sesame', 'Red Sesame', 'Mixed Sesame'],
  "Onion": ['Onion'],
  "Tomato": ['Tomato'],
  "Avocado": ['Avocado'],
  "Potato": ['Potato'],
  "Garlic": ['Garlic'],
  "Red Pepper": ['Red Pepper'],
  "Banana": ['Raw Bananas', 'Ripe bananas'],
  "Sorghum": ['Sorghum'],
  "Soybean": ['Soybean'],
  "Mango": ['Mango'],
  "Malt Barely": ['Malt Barely'],
  "Local Rice": ['Local Rice'],
  "Green Mung": ['Green Mung'],
  "Pineapple": ['Pineapple'],
};

const List<String> seasons  = ["bega", "kiramit", "belg", "tsedey"];